cloudfoundry/app-autoscaler-release

- NOTICE
There was no CloudFoundry.org Foundation in 2013. All contributions to this repo by CFF members seem to have started in 2016.
> corrected copyright start year

- templates/bosh-lite-manifest-template-v2.yml
Making v1 and v2 manifests templates consistent.
> Making postgres release version same as v1 manifest template

- src/acceptance/app/dynamic_policy_test.go
[#150799699]
1 Just close doneChan instead of trying to push bool into it to avoid
deadlock
2 Increase test app’s memory quota
> acceptance tests sometimes hung by channel deadlock

- example/property-overrides.yml
- jobs/metricscollector/spec
- templates/app-autoscaler-deployment.yml
-  Delegate DB calls to separate goroutine in the metrics collector
> Bump-up app-autoscaler

- src/acceptance/broker/broker_test.go
- Broker Acceptance test break for cf-cli version greater than 6.32
> Fix broker acceptance test for newer cf-cli versions

- jobs/apiserver/spec
- jobs/apiserver/templates/config.json.erb
- src/acceptance/api/api_suite_test.go
- src/acceptance/api/api_test.go
- src/acceptance/app/app_suite_test.go
- src/acceptance/app/dynamic_policy_test.go
- src/acceptance/app/recurring_schedule_policy_test.go
- src/acceptance/app/specificdate_schedule_policy_test.go
- src/acceptance/broker/broker_suite_test.go
- src/acceptance/config/config.go
- templates/app-autoscaler-deployment-fewer.yml
- templates/app-autoscaler-deployment.yml
In this PR,  we just add the deployment & acceptance changes for the build-in experience.  
All the default deployment options still aim to offer autoscaler as a service. 
Another document changes PR will be raised later to reflect how to deploy autoscaler as a build-in experience and how to config acceptance test with build-in experience.
> bump app-autoscaler to pick up build-in experience feature

- templates/app-autoscaler-deployment-fewer.yml
- templates/app-autoscaler-deployment.yml
There is a change in bosh cli release v4.0.1 to enforces that YAML anchors are already defined before they are referenced.
> https://github.com/cloudfoundry/bosh-cli/releases/tag/v4.0.1
> change the yaml anchors order to make sure anchors defined before they are referenced

- src/acceptance/app/dynamic_policy_test.go
The network connection is slow in the container when running acceptance test in concourse pipeline, resulting throughput scale out test failed as the throughput cannot reach 2 rps/s.
```
Summarizing 1 Failure:
• Failure [529.750 seconds]
AutoScaler dynamic policy when scaling by throughput when throughput is greater than scaling out threshold [It] should scale out 
/tmp/build/124e3615/app-autoscaler-git-release/src/acceptance/app/dynamic_policy_test.go:250
Timed out after 420.000s.
Expected
<int>: 1
to equal
<int>: 2
/tmp/build/124e3615/app-autoscaler-git-release/src/acceptance/helpers/helpers.go:259
Full Stack Trace
/tmp/build/124e3615/app-autoscaler-git-release/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:147 +0x439 …
```
> change scale out threshold of throughput from 2 to 1

- src/acceptance/assets/app/nodeApp/package.json
current nodejs version of the test application is 6.x and there is a warning message when staging application:
```
Downloading app package...
Downloaded app package (1.3M)
-----> Nodejs Buildpack version 1.6.45
-----> Installing binaries
engines.node (package.json): 6.x
engines.npm (package.json): unspecified (use default)
-----> Installing node 6.17.0
Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.0-linux-x64-cflinuxfs3-7d9e1436.tgz]
**WARNING** node 6.x will no longer be available in new buildpacks released after 2019-04-30.
See: https://github.com/nodejs/LTS
Using default npm version: 3.10.10
-----> Installing yarn 1.13.0
Download [https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-1.13.0-any-stack-125d40eb.tar.gz]
Installed yarn 1.13.0
-----> …
```
> upgrade nodejs vesion of test application

- example/operation/external-db.yml
The policy_db in the operator instance also needs to get the external DB settings.
> Add replace rule for instance operator and policy_db when external DB

- config/blobs.yml
- packages/changeloglockcleaner/packaging
- packages/eventgenerator/packaging
- packages/golang/packaging
- packages/golang/spec
- packages/metricscollector/packaging
- packages/metricsforwarder/packaging
- packages/metricsgateway/packaging
- packages/metricsserver/packaging
- packages/operator/packaging
- packages/scalingengine/packaging
Golang 1.11 is an archived release, and there are a few CVEs open.
> Update to Golang 1.13

- templates/app-autoscaler-deployment.yml
As it is needed for mTLS to work via the wildcard SANs, and it might not be enabled director-wide. Closes #210 
https://bosh.io/docs/dns/#links
> Add features: use_dns_addresses: true

- src/acceptance/assets/app/nodeApp/package.json
node 8.x.x will be deprecated soon. 
`**WARNING** node 8.x.x will no longer be available in new buildpacks released after 2019-12-01.`
> let the test nodejs app use default node engines

- src/acceptance/api/api_suite_test.go
> Deprecation warning: Use of the '-d' command-line flag option is deprecated in favor of the 'routes' property in the manifest. Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#routes for usage information. The '-d' command-line flag option will be removed in the future.
'-d' option is removed in the new cf cli.
> replace -d option in cf push to fix acceptence test

- src/acceptance/README.md
- src/acceptance/api/api_suite_test.go
- src/acceptance/app/app_suite_test.go
- src/acceptance/broker/broker_suite_test.go
- src/acceptance/config/config.go
- src/acceptance/helpers/helpers.go
When running the autoscaler acceptance tests, using a GA version of the CF CLI version 7, the tests fail because there is no longer a `-s` flag when running `cf marketplace`
In v7 the flags `-b` for broker and `-e` for offering exist instead.
Acceptance tests should check that service offering exists with appropriate name using CF CLI v7
---
When running the autoscaler acceptance tests where the autoscaler is deployed and globally available, `cf disable-service-access -o org-id` will fail. A new flag `enable_service_access` which defaults to true controls whether `enable-service-access` and `disable-service-access` are called.
---
> Acceptance tests should use CF CLI v7

- example/operation/alternative-vm-type.yml
This will be used when testing the pipeline via the `bosh/main-bosh-docker` image, as the default cloud config only contains the  a `default` vm type
> Added an example operations file to change the default vm type

- jobs/scheduler/templates/application.properties.erb
We have moved our applicationContext.xml to application.properties in the scheduler application.  Therefore, quartz configs are also required in scheduler job template  
For reference, please see https://github.com/cloudfoundry/app-autoscaler/pull/634
> add missing quartz properties (ref spring application context)

- templates/app-autoscaler-deployment.yml
This is the latest available 9.6.6 postgres release
> Bump postgres-release to v27

- Gemfile.lock
- jobs/golangapiserver/spec
- jobs/golangapiserver/templates/apiserver.yml.erb
- spec/jobs/golangapiserver/apiserver_spec.rb
Enable the ablitiy to rotate credentials for the service broker  by having multiple logins for past and new user/password combos
> Enable rotation credentials for service broker

- REQUIRED_OPS_FILES
Required with cf-deployment v17.x
> Enable nats tls by default

- jobs/metricsforwarder/spec
- jobs/metricsforwarder/templates/instance_identity_ca.crt.erb
- jobs/metricsforwarder/templates/metricsforwarder.yml.erb
- spec/jobs/metricsforwarder/metricsforwarder_spec.rb
This PR just removes all the ca_cert stuff that we thought was needed in mtls but actually was unnecessary and just complicates the process.
This relies on the changes from autoscaler to me merged in first.
https://github.com/cloudfoundry/app-autoscaler/pull/796
> Removing unnecessary ca Cert file for metricsforwarder mtls

- src/scheduler/pom.xml
Important: Security Vulnerability CVE-2021-45046
The Log4j team has been made aware of a security vulnerability, CVE-2021-45046, that has been addressed in Log4j 2.12.2 for Java 7 and 2.16.0 for Java 8 and up.
Summary: Apache Log4j2 Thread Context Message Pattern and Context Lookup Pattern vulnerable to a denial of service attack.
Details
It was found that the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations. This could allows attackers with control over Thread Context Map (MDC) input data when the logging configuration uses a Pattern Layout with either a Context Lookup (for example, $${ctx:loginId}) or a Thread Context Map pattern (%X, %mdc, or %MDC) to craft malicious input data using a JNDI Lookup pattern resulting in a denial of …
> CVE-2021-45046

- src/scheduler/pom.xml
Important: Security Vulnerability CVE-2021-45105
The Log4j team has been made aware of a security vulnerability, CVE-2021-45105, that has been addressed in Log4j 2.17.0 for Java 8 and up.
Summary: Apache Log4j2 does not always protect from infinite recursion in lookup evaluation.
Details
Apache Log4j2 versions 2.0-alpha1 through 2.16.0 did not protect from uncontrolled recursion from self-referential lookups. When the logging configuration uses a non-default Pattern Layout with a Context Lookup (for example, $${ctx:loginId}), attackers with control over Thread Context Map (MDC) input data can craft malicious input data that contains a recursive lookup, resulting in a StackOverflowError that will terminate the process. This is also known as a DOS (Denial of Service) attack.
Mitigation
From …
> Log4J 2.17.0

- style-guide/inspect-java-format-0.1.sh
```
❯ git commit -m "migration to mockito 4"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/C5326931/.cache/pre-commit/patch1640168034-64116.
java-formatter...........................................................Failed
- hook id: java-formatter
- exit code: 1
Running Checkstyle using /Users/C5326931/SAPDevelop/app-autoscaler-release/.cache/checkstyle-8.44-all.jar...
sed: -e expression #1, char 2: invalid usage of line address 0
rm: cannot remove '/Users/C5326931/SAPDevelop/app-autoscaler-release/style-guide/result.txt': No such file or directory
Running Checkstyle using /Users/C5326931/SAPDevelop/app-autoscaler-release/.cache/checkstyle-8.44-all.jar...
sed: -e expression #1, char 2: invalid usage of line address 0 …
```
> Fix java linter

- src/acceptance/bin/test_default
Concourse uses ginkgo directly to call the acceptance tests so they will still be run on bosh.ci.cloudfoundry.org.  Internally we are also using ginkgo directly too
> Skip the mtls tests by default

- jobs/eventgenerator/spec
- jobs/eventgenerator/templates/liquibase.properties
- jobs/golangapiserver/spec
- jobs/golangapiserver/templates/liquibase.properties
- jobs/metricsserver/spec
- jobs/metricsserver/templates/liquibase.properties
- jobs/operator/spec
- jobs/operator/templates/liquibase.properties
- jobs/scalingengine/spec
- jobs/scalingengine/templates/liquibase.properties
- jobs/scheduler/spec
- jobs/scheduler/templates/liquibase.properties
- liquibase-4-test.sh
- liquibase.properties
- src/db/pom.xml
**Liquibase 3.6.3 and 4.6.2 Output**
The upgrade from 3.6.3 to 4.6.3 works. It has correctly determined the filepaths.
```
id |    author    | liquibase |                              filename                              | exectype
----+--------------+-----------+--------------------------------------------------------------------+----------
1  | pradyutsarma | 3.6.3     | /var/vcap/packages/golangapiserver/api.db.changelog.yml            | EXECUTED
2  | fujitsu      | 3.6.3     | /var/vcap/packages/golangapiserver/api.db.changelog.yml            | EXECUTED
3  | paltanmoy    | 3.6.3     | /var/vcap/packages/golangapiserver/api.db.changelog.yml            | EXECUTED
1  | ying         | 3.6.3     | /var/vcap/packages/golangapiserver/servicebroker.db.changelog.json | EXECUTED
2  | qy …
```
> Upgrade liquibase 4.6.2

- src/acceptance/helpers/helpers.go
Also drops support for v6 CLI, which is no longer supported with current CF deployments: https://github.com/cloudfoundry/cli/wiki/Versioning-and-Support-Policy
> Add support for v8 CF CLI.

- src/scheduler/pom.xml
see https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement#status
> CVE-2022-22965: Update to Spring Framework 5.3.18

- .github/dependabot.yaml
`daily` means weekdays, see the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval)
> Schedule Dependabot update more often

- src/autoscaler/api/policyvalidator/policy_validator.go
- src/autoscaler/api/policyvalidator/policy_validator_test.go
As per the title suggests, this PR allows for an operator to apply a policy where `instance_min_count` can equal to `instance_max_count`. It still allows for the obvious check being that `max` is greater than `min` but it also allows for an application to be statically scaled to a given number without having to be unbound from the service.
> Allow minimum number of instances to equal maximum number of instances

- jobs/golangapiserver/spec
- jobs/golangapiserver/templates/apiserver.yml.erb
- src/acceptance/app/dynamic_policy_test.go
- src/acceptance/assets/app/nodeApp/app.js
- src/acceptance/assets/app/nodeApp/worker.js
- src/acceptance/broker/broker_test.go
- src/acceptance/config/config.go
- src/autoscaler/api/brokerserver/broker_handler.go
- src/autoscaler/api/config/config.go
- src/autoscaler/api/policyvalidator/policy_validator.go
- src/autoscaler/api/policyvalidator/policy_validator_test.go
- src/autoscaler/api/publicapiserver/public_api_handler.go
This change allows CPU threshold to be set in a more flexible way.
So far the threshold was hardcoded to 100% but now it's possible to provide values in the deployment manifest.
This is very useful if diego VMs have more than one CPU core and you want your app to scale when CPU usage is reported as more than 100%
In the nodejs app, multiple workers are now spun up to utilise multiple CPU
threads when trying to achieve a load of more than 100% CPU.
It is now possible to configure the tests to check that an app is able to scale up if CPU usage exceeds
an upper CPU threshold of over 100%.
We left the default at 100 so there is no change for and users who do not use this setting.
> Multi CPU scaling policies

- src/acceptance/api/api_test.go
- src/acceptance/helpers/helpers.go
- src/autoscaler/api/brokerserver/broker_handler.go
- src/autoscaler/api/policyvalidator/policy_validator.go
- src/autoscaler/api/policyvalidator/policy_validator_test.go
- src/autoscaler/api/publicapiserver/public_api_handler.go
- src/autoscaler/api/publicapiserver/public_api_handler_test.go
Extra fields in a policy should be silently ignored for backwards
compatibility, but never persisted or returned.
Closes #550
> Ignore extra fields in policies

- .github/workflows/rubocop.yaml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- Makefile
- jobs/golangapiserver/templates/apiserver.yml.erb
- spec/jobs/eventgenerator/eventgenerator_spec.rb
- spec/jobs/golangapiserver/apiserver_spec.rb
- spec/jobs/metricsforwarder/metricsforwarder_spec.rb
- spec/jobs/metricsgateway/metricsgateway_spec.rb
- spec/jobs/metricsserver/metricsserver_spec.rb
- spec/jobs/operator/operator_spec.rb
- spec/jobs/scalingengine/scalingengine_spec.rb
- spec/jobs/scheduler/scheduler_spec.rb
The API server specs already had the necessary config options, but they were not evaluated and set in the API server config.
As I had to touch the Ruby templates and tests I also added a `rubocop` `make` target and added a GitHub action to check PRs.
`rubocop` was configured with the `StandardRB` preset.
> Fix templates to allow enabling mTLS for public API endpoints

- .github/workflows/java-ci-lint.yaml
Since Sonar Cloud Maven plugin is used to scan scheduler project, SONAR_TOKEN should be passed as CLI argument/ or in pom.xml
**Resolution**
Pass SONAR_TOKEN as part of cli argument
[Failed sonar check](https://github.com/cloudfoundry/app-autoscaler-release/runs/6448812939?check_suite_focus=true#step:6:226)
> fix: use sonar token as cli parameters

- Makefile
- src/autoscaler/healthendpoint/health_readiness_test.go
- src/autoscaler/healthendpoint/server.go
If the username and password are empty then basic auth is not applied to the health/prometheus endpoint.
This means if onlu the username_hash and password_hash are supplied then basic auth is not configured the health/prometheus endpoint
> Security fix: Health endpoint not secured if just hashes supplied

- .github/workflows/shellcheck.yaml
- .tool-versions
- scripts/generate_test_certs.sh
- src/autoscaler/Makefile
- src/scheduler/scripts/generate_unit_test_certs.sh
- Replace `go get` and `brew install` with `go run`
Instead of installing tools such as `certstrap` in an OS-dependent way,
use `go run` to [run them directly](https://www.alexedwards.net/blog/using-go-run-to-manage-tool-dependencies).
- Add `shellcheck` GHA
> Replace `go get` and `brew install` with `go run`

- src/autoscaler/api/cmd/api/main.go
- src/autoscaler/api/config/config.go
- src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
- src/autoscaler/eventgenerator/config/config.go
- src/autoscaler/healthendpoint/health_readiness.go
- src/autoscaler/healthendpoint/health_readiness_test.go
- src/autoscaler/healthendpoint/server.go
- src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
- src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
- src/autoscaler/metricsforwarder/config/config.go
- src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
- src/autoscaler/metricsgateway/config/config.go
- src/autoscaler/metricsserver/cmd/metricsserver/main.go
- src/autoscaler/metricsserver/config/config.go
- src/autoscaler/models/health.go
- src/autoscaler/models/health_test.go
- src/autoscaler/operator/cmd/operator/main.go
- src/autoscaler/operator/config/config.go
- src/autoscaler/scalingengine/cmd/scalingengine/main.go
- src/autoscaler/scalingengine/config/config.go
- Disabling readiness by default untill cache is available to prevent DOS
- Fixing up the tests and merging main
- Update server.go
- Update health_readiness.go
- Update health_readiness_test.go
- Addition of Thread safe cacheing with a ttl of 30s for the /health/readiness endpoint
> Addition of 30s cache on the /health/readiness endpoint

- src/common/databasechangelog-primarykey.yml
When using external mysql database the following error is logged:
```
Starting Liquibase at 11:50:14 (version 4.9.1 #1978 built at 2022-03-28 19:39+0000)
Running Changeset: databasechangelog-primarykey.yml::1::aqan213
Unexpected error running Liquibase: Migration failed for change set databasechangelog-primarykey.yml::1::aqan213:
Reason: liquibase.exception.DatabaseException: Multiple primary key defined [Failed SQL: (1068) ALTER TABLE autoscaler.DATABASECHANGELOG ADD PRIMARY KEY (id, author, filename)]
```
Checking the database we do see the primary keys:
and the change to be executed at least once:
Though the constraint name is `PRIMARY`
This is already disccussed [here](https://stackoverflow.com/a/60235230)
With that in mind, the following change updates the `preConditions` to match on …
> Fix database migration for MySQL

- ci/autoscaler/tasks/deploy-previous-autoscaler.yml
- ci/autoscaler/tasks/release-autoscaler.yml
- ci/autoscaler/tasks/update-sdk/task.yml
At someplaces, old ci paths were used which caused the ci to broke. This PR corrects those references
> fixed stale ci paths

- Makefile
- README.md
- src/autoscaler/Makefile
- src/autoscaler/api/brokerserver/broker_server_suite_test.go
- src/autoscaler/api/schedulerutil/schedulerutil.go
- src/autoscaler/eventgenerator/generator/evaluator.go
- src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
- src/autoscaler/integration/integration_golangapi_metricsserver_test.go
- src/autoscaler/integration/integration_golangapi_scalingengine_test.go
- src/autoscaler/integration/integration_golangapi_scheduler_test.go
- src/autoscaler/integration/integration_metricsgateway_metricserver_eventgenerator_scalingengine_test.go
- src/autoscaler/integration/integration_operator_others_test.go
- src/autoscaler/integration/integration_scheduler_scalingengine_test.go
- src/autoscaler/integration/integration_suite_test.go
- src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManager.java
1. Fixed some internal error handling for 
-- POST `/v1/apps/{appid}/scale` on scaling engine
-- DELETE `/v1/apps/{appId}/schedules`
These continue to return 500 if the appId is too long but no longer panic internally.
1. Improved the tracebility of some of the internal test ids to help track down some intermittant test failures
> Id error handling fixes and creating traceable test id's

- ci/autoscaler/scripts/update-dns-servers.sh
Removal was unnecessary: After fixing the DNS entries, the job can be retriggered.
Reverts cloudfoundry/app-autoscaler-release#777
> Revert "Don't fail `setup-infrastructure` job o enable downstream job after manual action"

- ci/autoscaler/tasks/update-sdk/create_pr.sh
to not confuse the acceptance tests workflows
> update-sdk: only set `dependencies` label

- src/autoscaler/eventgenerator/client/metric_server_client.go
Webscan is doing some test with appId like "9e511e42-4e48-4da8-8118-a8a47a8f35f4\"'/@=*[]()" and this cause eventgenerator job to crash since path is NULL.
So we have to check err variable
> Prevent eventgenerator crash when appId is not valid

- ci/autoscaler/pipeline.yml
Add scale-to-one-az-addon-parallel-cats.yml:
> Use this after the scale-to-one-az ops file to scale up to minimal size
> in order to run CATS quickly without flakes and 12 threads
More context in https://github.com/cloudfoundry/cf-deployment/pull/981 - as far as I understand it, it more or less restores the sizing to what it was before.
> CI: Scale CF for parallel CATS

- .github/workflows/generate.yaml
- .github/workflows/tidy-go-mod.yaml
- .tool-versions
- Makefile
- jobs/golangapiserver/spec
- src/autoscaler/go.mod
- `go run` the right `golangci-lint` version
- Run `scripts/update` and ensure that it has been run via GHA
- Replace UnicornGlobal/has-changes-action (see https://github.com/UnicornGlobal/has-changes-action/issues/5#issuecomment-1126126476)
> run `scripts/update`

- src/common/utils.sh
In a context like K8s,  where a job is a container the following check could be not accurate
https://github.com/cloudfoundry/app-autoscaler-release/blob/064e00649a8b8db86b63b2428c6515aace418c30/src/common/utils.sh#L18
In general inside the container a number of processes really small exist...
```
/:/var/vcap/jobs/operator# ps -ef
UID         PID   PPID  C STIME TTY          TIME CMD
root          1      0  0 08:37 ?        00:00:00 /usr/bin/dumb-init -- /var/vcap/all-releases/container-run/container-run --post-start-name /var/vcap/jobs/operator/bin/post-start --job-name operator --process-n
root          6      1  0 08:37 ?        00:00:00 /var/vcap/all-releases/container-run/container-run --post-start-name /var/vcap/jobs/operator/bin/post-start --job-name operator --process-name operator …
```
> Improve pid_guard() logic

- operations/add-releases.yml
- templates/app-autoscaler-deployment.yml
Provides PostgreSQL 11.2 - see #478
> Bump `postgres` release to 36

- Makefile
to run acceptance tests.
As it runs ./ci/autoscaler/scripts/run-acceptance-tests.sh you can set
various environemnt variables to influence its run, .e.g:
- `DEPLOYMENT_NAME`
- `SUITES`
- `NODES`
- `GINKGO_OPTS`
It expects that you have checked out `app-autoscaler-env-bbl-state`
next to the `app-autoscaler-release` repo, but if you have your own
location for BBL state folder running the app-autoscaler you may point
to it via `BBL_STATE_PATH`.
> Add `make acceptance` target

- src/autoscaler/db/sqldb/appmetric_sqldb.go
- src/autoscaler/db/sqldb/binding_sqldb.go
- src/autoscaler/db/sqldb/instancemetrics_sqldb.go
- src/autoscaler/db/sqldb/policy_sqldb.go
- src/autoscaler/db/sqldb/scalingengine_sqldb.go
- src/autoscaler/db/sqldb/scheduler_sqldb.go
- src/autoscaler/db/sqldb/sqldb_suite_test.go
- src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
While iterating over a query table it is possible to get an error while retrieving the next row. 
This is only reported in the row.Err() function and the next returns false. 
This means that you need to return the error from the row.Err if you itterate so that you know if you iterated over all the results for the query.
> Audit on Db connetions lead to fix for returning DB errors correctly

- Makefile
- src/autoscaler/cf/client.go
- src/autoscaler/cf/drain_transport.go
- src/autoscaler/cf/drain_transport_test.go
Fix for https://github.com/cloudfoundry/app-autoscaler-release/issues/814
We added a DrainTransport Wrapper for the CF Client, as advised here https://github.com/google/go-github/pull/317. It makes sure, that all bytes are read from the response before the body is closed.
co-authored: @KevinJCross
> Fixes not reusing tcp connections by reading all bytes from the response body #814

- src/autoscaler/Makefile
- src/autoscaler/cf/client.go
- Mark logs by `retryablehttp`
- Ensure binaries are compiled dynamically
> Misc supportability fixes

- jobs/Gemfile
- jobs/Gemfile.lock
- jobs/eventgenerator/templates/eventgenerator_ctl
- jobs/golangapiserver/templates/apiserver_ctl.erb
- jobs/metricsforwarder/templates/metricsforwarder_ctl
- jobs/metricsgateway/templates/metricsgateway_ctl
- jobs/metricsserver/templates/metricsserver_ctl
- jobs/operator/templates/operator_ctl
- jobs/scalingengine/templates/scalingengine_ctl
- jobs/scheduler/templates/scheduler.erb
- src/common/utils.sh
If there is no ulimits set on the system the default ulimit is normally 1024.
This pr checks that the file handles limit (tcp connecions) is minimum 16k. If it is currently unlimited then it does not change this.
This fix is to help reduce the effect of https://github.com/cloudfoundry/app-autoscaler-release/issues/814
As evidence:
```
scalingengine/x:/var/vcap/bosh_ssh/x5# monit status scalingengine
The Monit daemon 5.2.5 uptime: 8m 
Process 'scalingengine'
status                            running
monitoring status                 monitored
pid                               7845
parent pid                        1
uptime                            8m 
children                          2
memory kilobytes                  15972
memory kilobytes total            15972
memory percent …
```
> Setting a minimum file handle limits to 16k

- jobs/golangapiserver/templates/apiserver_ctl.erb
- jobs/metricsforwarder/templates/metricsforwarder_ctl
- jobs/metricsgateway/templates/metricsgateway_ctl
- jobs/metricsserver/templates/metricsserver_ctl
This is necessary since on k8s the corresponding jobs cannot start as I replicated manually below....
```
/:/var/vcap/jobs/metricsserver# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127799
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, …
```
> Remove old ulimit setting which is obsoleted by #873

- Makefile
- ci/autoscaler/scripts/silence_prometheus_alert.sh
This simple make target is used to silence prometheus alerts against a deployment for 8 hours.
Helpful for local development
usage
`make silence-alerts DEPLOYMENT_NAME=autoscaler-<PR_NUMBER>`
> Silence prometheus alerts for 8 hours using make target

- templates/app-autoscaler.yml
The host property was missing in the manifest for the operator vm
**Problem**
```
{"data":{"error":"Put \"https://xxxxxxxxv1/syncSchedules\": dial tcp: lookup ......on 169.254.0.2:53: no such host","session":"15"},"log_level":2,"log_time":"2022-10-13T08:33:25Z","message":"operator.scheduler-sync.failed-to-send-sync-scheduler-request","source":"operator","timestamp":"1665650005.884648085"}
```
**solution**
Add the missing scheduler host property in the manifest
> Fix for missing scheduler host property in the manifest for the operator vm

- ci/terragrunt/app-autoscaler/concourse/teams.tf
Adds @wg-app-runtime-interfaces-autoscaler-reviewers to "app-autoscaler" Concourse team owners.
> Add reviewers GH team as Concourse team owners

- Makefile
- src/acceptance/cleanup.sh
- adding acceptance cleanup target
- Fixing bug in acceptance cleanup script
- When there is an issue with deleting the service binding there was a bug in creating the list of services to purge. This resulted in a failure to delete the organisations
> fix bug in the acceptance test cleanup.sh

- ci/autoscaler/scripts/deploy-autoscaler.sh
- jobs/eventgenerator/spec
- jobs/eventgenerator/templates/eventgenerator.yml.erb
- operations/enable-log-cache-via-uaa.yml
- spec/jobs/eventgenerator/eventgenerator_spec.rb
- src/autoscaler/eventgenerator/client/log_cache_client.go
- src/autoscaler/eventgenerator/client/metric_client_factory.go
- src/autoscaler/eventgenerator/client/metric_client_factory_test.go
- src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
- src/autoscaler/eventgenerator/config/config.go
- src/autoscaler/fakes/fake_go_log_cache_client.go
- src/autoscaler/models/uaa_creds.go
- Establish eventgenerator connection with logcache via UAA
-  If UAA creds are provided , we favor the OAUTH HTTP implementation for https://github.com/cloudfoundry/go-log-cache in eventgenerator. Otherwise, GPRS based with metricsforwarder
> Establish eventgenerator connection with logcache via UAA

- ci/autoscaler/pipeline.yml
- ci/autoscaler/set-pipeline.sh
- ci/autoscaler/tasks/check-diego-cell-count.yml
- ci/autoscaler/tasks/cleanup-autoscaler-deployments.yml
- ci/autoscaler/tasks/cleanup-autoscaler.yml
- ci/autoscaler/tasks/deploy-autoscaler.yml
- ci/autoscaler/tasks/deploy-previous-autoscaler.yml
- ci/autoscaler/tasks/make/make.yml
- ci/autoscaler/tasks/register-broker.yml
- ci/autoscaler/tasks/release-autoscaler.yml
- ci/autoscaler/tasks/run-acceptance-tests.yml
- ci/autoscaler/tasks/run-integration-tests.yml
- ci/autoscaler/tasks/run-unit-tests.yml
- ci/autoscaler/tasks/update-sdk/task.yml
- ci/infrastructure/pipeline.yml
- ci/infrastructure/tasks/check-for-existing-deployments.yml
- ci/infrastructure/tasks/combine-ops.yml
- ci/infrastructure/tasks/deploy-prometheus.yml
- ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/pipeline.yml
`docker-image` is failing on concourse 7.8.3
https://github.com/concourse/registry-image-resource
> replace docker-image with registry-image (concourse 7.8.3)

- src/acceptance/assets/app/nodeApp/app_manifest.yml
Upon pushing a cf app, buildpack options is used. Previously, the sample node JS app uses the buildpack option from he manifest. 
The current implementation used buidpack options as cli var 
**Usage** 
[https://github.com/cloudfoundry/app-autoscaler-release/blob/main/src/acceptance/helpers/apps.go#L97](https://github.com/cloudfoundry/app-autoscaler-release/blob/main/src/acceptance/helpers/apps.go#L97)
> use buildpack option as var (instead the one defined in app manifest)

- ci/infrastructure/scripts/deploy-prometheus.sh
Prometheus deployment continue to use ubuntu-bionic stemcell 
Revert [de44df72fa9d51db1f96bf3c0b4fbc36606e28de](https://github.com/cloudfoundry/app-autoscaler-release/commit/de44df72fa9d51db1f96bf3c0b4fbc36606e28de)
> Revert prometheus deployment with ubuntu-jammy change

- src/acceptance/app/dynamic_policy_test.go
Tweaking the limits of the memory utilisation tests to work on more environments.
#1059
> Fix #1059: Tweak the mem util test limits to work on more environments

- src/scheduler/pom.xml
Changed MySQL maven dependency in the scheduler pom (as listed in [affected Build ](https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/3893024545/jobs/6645365887#step:4:129))
```
....
[INFO] ---------------< org.cloudfoundry.autoscaler:scheduler >----------------
[INFO] Building scheduler 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
Warning:  The artifact mysql:mysql-connector-java:jar:8.0.31 has been relocated to com.mysql:mysql-connector-j:jar:8.0.31: MySQL Connector/J artifacts moved to reverse-DNS compliant Maven 2+ coordinates.
[INFO] ....
......
```
[Maven Docs](https://search.maven.org/artifact/mysql/mysql-connector-java/8.0.31/jar)
> Use MySQL new mvn Coordinates starting from v8.0.31

- src/autoscaler/api/brokerserver/broker_server.go
- src/autoscaler/healthendpoint/server.go
- templates/app-autoscaler.yml
Configured passwords for the servicebroker and the healthendpoints were
previously (before #1249) [silently truncated to the first 72 bytes][1].
This change restores the truncation to the first 72 bytes, but adds an
error level warning (as `lager` does not have a dedicated warning
level), documenting this truncation, so previously configured passwords
longer than 72 bytes will continue to work unchanged.
Prior to this PR, since #1249, passwords longer than 72 bytes would cause an error.
[1]: https://github.com/golang/go/issues/36546
> Restore previous handling of long passwords

- .github/workflows/postgres.yaml
9.6 is out of maintenance: https://endoflife.date/postgresql
> Do not test with PostgreSQL 9.6 anymore, but with 15

- src/acceptance/helpers/apps.go
- src/acceptance/helpers/cleanup.go
- src/acceptance/run_performance/run_performance_suite_test.go
- src/acceptance/setup_performance/setup_performance_suite_test.go
`cf download-droplet` fails to download app droplet
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>GET
application/json
1679504433
/droplet-q_ioaqk91dw/41/c8/41c8e0f4-d92b-41ce-895b-4fdd7ae21751/97f60524ba3df900f4baa4b485f014fe8f0efc46</StringToSign></Error>
```
Use Cf curl for downloading droplet from blobstore
This issue was already reported [here](https://github.com/cloudfoundry/cli/issues/1165#issuecomment-310925846)
> Use CF Rest API to Download Droplet

- jobs/scheduler/templates/scheduler.yml.erb
- spec/fixtures/scheduler.yml
- spec/jobs/scheduler/scheduler_spec.rb
- src/scheduler/src/main/resources/application.yml
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/conf/DataSourceConfigTest.java
Having YAML configurations, strings starting with numbers e.g. 229259e82505 could infer unwanted data types e.g. Integer, Float, Double, etc. As a result, the scheduler app does not connect to an underlying database and raises an exception.
For instance,  string _229259e82505_ (without quotes) as the username of the datasource is interpreted as "Infinity"(non-existent user in the database)
**FIX**
Treating username and password as String in double quotes (") to ensure the string credentials are passed to the database correclty
**Stacktrace**
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfigurat …
```
> Fix Scheduler Database Credentials Syntax in  Bosh Jobs Template

- templates/app-autoscaler.yml
Default values are according to https://docs.cloudfoundry.org/api/credhub/version/2.9/
```
key_length: 2048
duration: 365
```
but we want
```
key_length: 4096
duration: 180
```
> Set `key_length` and `duration` on all certs

- jobs/scheduler/monit
- jobs/scheduler/spec
- spec/fixtures/monit
- spec/jobs/scheduler/scheduler_spec.rb
Reverts cloudfoundry/app-autoscaler-release#2074
> Revert "Scheduler use health endpoint monit"

- ci/infrastructure/scripts/deploy-prometheus.sh
Due to <https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v29.0.0>, to reflect the comming change in the logging-infrastructure, loggregator-firehose has been moved to the deprecated-folder.
> Fix path to file in prometheus-release;

- renovate.json
As runners are scarce in the `cloudfoundry` org,
we want to limit the number of concurrent PRs.
Every renovate PR gets rebased after every commit to main for
[good reasons](https://docs.renovatebot.com/configuration-options/#rebasewhen).
This means if there are the default `10` PRs open concurrently,
merging one PR currently triggers at least 9 * 31 = 279 workflows.
I chose the value of `2` so that if one PR fails to validate
consistently there's a second slot for other PRs. If two PRs
fail to validate consistently, probably a deeper look is necessary
anyways.
> Reducing the `prConcurrentLimit` to `2`

- src/scheduler/pom.xml
- src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/DataSourceConfig.java
- src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/health/DbStatusCollector.java
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplicationTest.java
HikariCP is the default Spring Boot database connection pool
implementation and the current implementation of choice.
> Replace DBCP2 database connection pool implementation with HikariCP

- src/acceptance/api/basic_auth_test.go
- src/acceptance/config/config.go
Hi,
The way the basic-auth tests currently determine their target urls is only ever going to work if the endpoints follow a very specific naming scheme (curiously, related to the autoscaler service plan name of the deployment).
This change allows these urls to be explicitly overridden via the e.g. `eventgenerator_health_endpoint` config parameter. Not particularly pretty, but retains the old attempt at autodiscovery when these parameters aren't specified.
> acceptance tests: allow overriding of component health endpoints

- templates/app-autoscaler.yml
Passwords are used when communicating with other systems and may not be
changed unilateraly.
This partially reverts commit 46b760ed2671a82edd01f7ebeafed244bee3ff98.
> fix(manifest): Do not set passwords to autoconverge

- .tool-versions
- ci/dockerfiles/autoscaler-tools/Dockerfile
- renovate.json
- Revert "chore(deps): update dependency golang to v1.21.5 (#2421)"
- fixup! Fix CodeQL scanning (#2215)
> fix(codeql): disable renovate golang updates

- api/scaling-history-api.openapi.yaml
- src/autoscaler/integration/integration_golangapi_scalingengine_test.go
- src/autoscaler/integration/integration_suite_test.go
to not break backwards compatibility.
If designing this API from scratch we would probably just omit this
value.
> Document that `-1` is our "not applicable" value

- src/autoscaler/operator/applicationsyncer.go
- src/autoscaler/operator/applicationsyncer_test.go
- src/autoscaler/operator/appmetricsdb.go
- src/autoscaler/operator/cmd/operator/main.go
- src/autoscaler/operator/instancemetricsdb.go
- src/autoscaler/operator/scalingenginedb.go
- src/autoscaler/operator/schedulersynchronizer.go
The `operator` is able to generate quite a bit of load on the DB and
should log on info level when it is working.
> chore(operator): Make operator a bit chattier

- ci/autoscaler/pipeline.yml
We have quite often seen tests jobs stop progressing and staying in a
running state for days until manually terminated.
> chore(ci): add timeouts to test steps

- .github/workflows/update-all-golang-dependencies.yaml
- Makefile
As indirect dependencies are not updated unless necessary by renovate (c.f. the [feature request to add lockfile updates for Go to renovate](https://github.com/renovatebot/renovate/issues/9578)) this PR adds a worflow scheduled monday mornings to create a PR updating *all* dependencies.
> feat(ci): update all golang dependencies weekly

- src/autoscaler/helpers/loggregator_logger.go
By default, a regular `metricsforwarder` deployment has the log level configured as `info`: https://github.com/cloudfoundry/app-autoscaler-release/blob/a993d5635879c6d32e0bc8a940d58a27881b5392/jobs/metricsforwarder/spec#L33-L35
The client which sends metrics uses a custom logger implementation: https://github.com/cloudfoundry/app-autoscaler-release/blob/fda280de2d3173d7a6898f8cc86d6d4a1192aef6/src/autoscaler/metricsforwarder/forwarder/metric_forwarder.go#L37. The custom logger implementation logs messages with level `debug` when `Printf` is called: https://github.com/cloudfoundry/app-autoscaler-release/blob/fda280de2d3173d7a6898f8cc86d6d4a1192aef6/src/autoscaler/helpers/loggregator_logger.go#L19
Interface method `Printf` is called by the client when erros occured while sending logs: …
> Print errors occured while sending metrics by default

- .github/workflows/postgres.yaml
AWS only offers TLS 1.3 in AWS RDS PostgreSQL 16, so we should test PostgreSQL version 16, in case someone wants to run app-autoscaler-release on it.
> Add PostgreSQL version 16 to test matrix

- renovate.json
to address the OpenSSF scorecard "Pinned-Dependencies" findings.
> Switch to `renovate` `best-practices` preset

- src/acceptance/assets/app/go_app/deploy.sh
It can happen that `use_existing_space` or `use_existing_org` is not set which causes the script to fail.
Let's default to `false` if any of `use_existing_space` or `use_existing_org` is not set propertly.
> Improve test-app deployment script

- ci/dockerfiles/autoscaler-tools/Dockerfile
Apparently, the package name was changed from `google-cloud-sdk` to
`google-cloud-cli`, see also
https://cloud.google.com/sdk/docs/install#deb
and on that page
> NOTE: For releases prior to 371.0.0, the package name is google-cloud-sdk
> fix(deps): `google-cloud-cli` download in `app-autoscaler-release-tools`

- ci/autoscaler/tasks/update-sdk/update_golang_package.sh
- ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/src/go.mod
- go.work
- src/acceptance/assets/app/go_app/go.mod
- src/acceptance/go.mod
- src/autoscaler/Makefile
- src/autoscaler/go.mod
- src/changelog/go.mod
- src/changeloglockcleaner/go.mod
As of Go `1.21`, versions specified in `go.mod` files are treated not as a guideline but as a strict rule. Also, `go 1.21` is automatically being mapped to `1.21.0`.
The following example basically says that Go `1.21.0` is required 
https://github.com/cloudfoundry/app-autoscaler-release/blob/13755c96c1458f27c88c3ca3762c6d8d07663900/src/autoscaler/go.mod#L3
Which causes problems because the "`1.21` -> `1.21.0` mapping" doesn't work for `go.work` files
https://github.com/cloudfoundry/app-autoscaler-release/blob/13755c96c1458f27c88c3ca3762c6d8d07663900/go.work#L1
[Example of a failing CI build](https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/8258040332/job/22589620245#step:5:302):
```bash
go.work file requires go >= 1.21.0, but go.work lists go 1.21.
```
* bump to exact …
> Bump to exact Go versions during `update-golang`

- Makefile
- scripts/compile-acceptance-tests.sh
- src/acceptance/bin/test
Go tries to download a specific toolchain version whenever the required version is not available on the system. The following PR introduced the exact Go toolchain version pinning #2757.
Requiring an exact Go toolchain version can make the acceptance tests execution fail in an environment that has no connectivity to the public internet. Here is a sample failure from an execution in China which tries to download a required toolchain version:
```
download go1.21.4: golang.org/toolchain@v0.0.1-go1.21.4.linux-amd64: Get "https://proxy.golang.org/golang.org/toolchain/@v/v0.0.1-go1.21.4.linux-amd64.zip": dial tcp 172.217.163.49:443: i/o timeout
```
Compile test suites and ginkgo CLI for 
* `linux` (`amd64`, `arm64`) 
* `darwin` (`amd64`, `arm64`)
Acceptance test executions with no public …
> fix(acceptance-tests): compile test suites and ginkgo cli for

- renovate.json
Due to the limited time, 6 hours per weekday, renovate PRs were piling up on weekends.
The preset [`schedule:nonOfficeHours`](https://docs.renovatebot.com/presets-schedule/#schedulenonofficehours) gives more time, including the whole weekend.
> chore(deps): Increase time for renovate PRs

- src/acceptance/app/custom_metric_test.go
This fix checks the expections of the custom metrics tests if mTLS authentication is used
> Fix Custom Metrics Acceptance Test (mTLS)

- ci/autoscaler/scripts/run-integration-tests.sh
- ci/autoscaler/scripts/run-unit-tests.sh
Not all tests where run, as the logic in the Concourse scripts was
duplicating the functionality in the `Makefile` but was out-of-date.
In particular, the `go_app` tests were not executed on Concourse.
We want our `Makefile` to be the central CI entry-point, thus we just
call `make` to run unit and integration tests.
> chore(ci): Run unit and integration tests using make

- .github/workflows/dependency-updates-post-processing.yaml
The workflow could be triggered by both pushes and PRs.
However, the PR trigger was misconfigured to require a PR against
`renovate/**`, when a renovate PR would naturally be against `main`.
This meant, that the `push` event was the one to trigger. However, in
this case the `hmarr/auto-approve-action` would fail with
> This action must be run using a `pull_request` event or have an
explicit `pull-request-number` provided
Instead of fixing the workflow when triggered by the `push` event, it
was fixed to correctly and only run when triggered by the `pull_request`.
> fix(ci): Add auto-approve step for PRs by renovate[bot

- src/autoscaler/go.mod
- src/autoscaler/go.sum
The dependency `cfhttp/v2` has not been updated for more than a year.
Renovate has been complaining about the cfhttp repo for some time now:
> Renovate failed to look up the following dependencies:
> `Could not determine new digest for update (go package code.cloudfoundry.org/cfhttp/v2).`
> Files affected: `src/autoscaler/go.mod`
The issue has been reported to [ARP in their Slack channel](https://cloudfoundry.slack.com/archives/C02HNDJB31R/p1713518531547079).
Until the underlying gets fixed and Renovate can create an update PR
I've created a manual update using
```
GOPROXY=direct go get -u code.cloudfoundry.org/cfhttp/v2
```
> chore(deps): Update `cfhttp/v2`

- ci/autoscaler/pipeline.yml
- ci/autoscaler/tasks/update-sdk/task.yml
- ci/infrastructure/pipeline.yml
The ssh-key of `autoscaler-ci-bot` is not capable of bypassing the branch protection rules. This is due to the fact that this user is no admin on this repo here. 
This breaks the release pipeline when pushing the release https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/release/builds/33#L65fa0435:11:12
Make use of a brand new deploy key added to this repo here issued for `ApplicationAutoscaler@sap.com` within the git-resources.
> fix(release): use deploy keys for git-resources

- src/acceptance/app/dynamic_policy_test.go
- src/acceptance/helpers/helpers.go
- src/autoscaler/envelopeprocessor/envelope_processor.go
- src/autoscaler/envelopeprocessor/envelopeprocessor_test.go
- src/autoscaler/eventgenerator/aggregator/metric_poller.go
- src/autoscaler/eventgenerator/client/log_cache_client.go
- src/autoscaler/eventgenerator/client/log_cache_client_test.go
- src/autoscaler/eventgenerator/client/metric_client_factory.go
- src/autoscaler/eventgenerator/client/metric_client_factory_test.go
- src/autoscaler/eventgenerator/client/metric_server_client.go
- src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_test.go
After the log-cache enablement with 3a, we've received a bug stating that `responsetime` and `throughput` are no longer working. It turned out, that the envelopes are being read via REST API which has a default of 100 maximum envelopes per response:
* https://github.com/cloudfoundry/log-cache-release/tree/main/src#get-apiv1readsource-id
* https://github.com/cloudfoundry/app-autoscaler-release/blob/d02b7b849e76b21335d1e720637f4cb57c91f693/src/autoscaler/eventgenerator/client/log_cache_client.go#L98
Using 100 envelopes to calculate the average `throughput` and `responsetime` for the last x seconds breaks the calculations. The following example shows that the limited set of envelopes causes `throughput` (a.k.a. requests per seconds) to not grow beyond 3:
* 100 envelopes
* polling interval 40 …
> fix(eventgenerator): use PromQL API for metric types `throughput` and `responsetime`

- .envrc
- flake.lock
- flake.nix
If you don't have `devbox` installed the `.envrc` would error out.
First check for `devbox` and then `nix`, restoring plain Nix usage as
well.
The package definitions for `app-autoscaler-cli-plugin` and
`bosh-bootloader` were duplicated in the root and `local-flake` flakes.
Reuse `local-flake` package definitions in main flake
> feat(direnv): Check if `devbox` is installed before invoking it

- .envrc
- src/autoscaler/db/db.go
- src/autoscaler/db/sqldb/scalingengine_sqldb.go
- src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
- src/autoscaler/db/sqldb/sqldb_suite_test.go
- src/autoscaler/operator/scalingenginedb.go
- src/autoscaler/operator/scalingenginedb_test.go
The table `scalingcooldowns` will gain an entry once an app is scaled.
This entry is never removed, thus a resource leak is created.
The table can get so big, that a simple select starts to take time (as
there is no index on the table).
The table is now periodically cleaned by the `operator`.
> fix(operator): Clean up scaling cooldowns

- .tool-versions
- devbox.json
- devbox.lock
- renovate.json
This PR brings https://github.com/cloudfoundry/app-autoscaler-release/pull/2619 also to the devbox environment.
> fix(devbox): Downgrade `bosh-cli` so that `make deploy-autoscaler` works on macOS

- ci/autoscaler/scripts/register-broker.sh
When having multiple CI-pipelines in Concourse, during the acceptance tests, the `register-broker`-job tries to clean up more service brokers than it should be. This leads to the fact, that a service broker get's deleted which shouldn't be but the actual to be deleted one stays untouched.
Example: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance/builds/1310#L664ad3ee:19:58
This is the error-prone code line: 
https://github.com/cloudfoundry/app-autoscaler-release/blob/b9a590adb116bc70405731033a896c66d880c477/ci/autoscaler/scripts/register-broker.sh#L17
Example why `grep`ping is not a good because it returns more than one service-broker: 
```
❯ cf service-brokers | grep …
```
> fix(acceptance): use CF API to check if broker exists instead of `grep`ping from `cf`-cli

- src/acceptance/bin/test_default
- src/acceptance/broker/broker_test.go
Previously we backed some assumptions into our plan update tests:
Their must be at least two plans, the first being updatable, and another with a specific name that should not be updatable.
This made the tests very dependent on the configuration chosen by the platform operator.
We now dynamically choose the first updatable plan and update to second.
If there are no two plans or none is updatable, we skip the test
The test testing that you cannot update from the first plan has been removed, as this is already guaranteed by the Cloud Controller, so the test was just excercising Cloud Controller code.
> fix(acceptance): fix naming of plan update tests names

- src/acceptance/app/cf_metadata_test.go
The test cases `cf_metadata_test` were marked with the smoke test
labels.
This is not warranted, as smoke tests should be minimal.
Remove the label.
> fix(acceptance): Remove smoke test label from `cf_metadata_test`

- ci/dockerfiles/autoscaler-tools/Dockerfile
bosh scp needs the `nc` binary in order to run. This is provided in the netcat package
> Add netcat to dockerfile to use bosh scp

- ci/scripts/delete-pipeline.sh
The additional space between param and value assignment breaks `make delete-pipeline`
```console
❯ make delete-pipeline                   
+ target=app-autoscaler-release
+ check-login
+ fly -t app-autoscaler-release status
logged in successfully
+ delete-pipeline ''
++ fly  👹--target= app-autoscaler-release pipelines👹  --json 
error: Unknown command `app-autoscaler-release'. Please specify one command of: abort-build, active-users, archive-pipeline, builds, check-resource, check-resource-type, checklist, clear-resource-cache, clear-task-cache, clear-versions, completion, containers, curl, delete-target, destroy-pipeline, destroy-team, disable-resource-version, edit-target, enable-resource-version, execute, expose-pipeline, format-pipeline, get-pipeline, get-team, help, hide-pipeline, …
```
> fix(ci): fix `fly` param value assignment so that `make delete-pipeline` works

- README.md
Seems like GitHub doesn't render the `<br/>`-tags properly. That's why the new line is messed up:
Inline the commands and get rid of custom HTML-tags.
Removed the Category column which didn't add any value but simply ate up screen-width
> fix(readme): drop HTML-tags to fix rendering

- ci/autoscaler/scripts/deploy-autoscaler.sh
Adds missing environment variable to fix issue on concourse pipeline:
broken job: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-log-cache-syslog-cf/builds/10
job with fix: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release-fix-missing-metricsforwarder-host-variable/jobs/acceptance-log-cache-syslog-cf/builds/1
> Adds missing variable to deploy-autoscaler script

- ci/autoscaler/pipeline.yml
Accidentally, the `acceptance-log-cache-syslog`-test was configured to have a `metricsforwarder` sending metrics directly to the Log Cache syslog server: https://github.com/cloudfoundry/app-autoscaler-release/pull/2913/files#diff-10ff83017bf5f3630e6c372c3aa8dc981a23f71cdc48c725cd17509d8d757a03R40
This should not be the case, `acceptance-log-cache-syslog` should run with a `metricsforwarder` sending metrics to `loggr-syslog-agent` (as it was before), see also #2685.
Don't apply `enable-metricsforwarder-via-syslog-agent.yml` during runs of `acceptance-log-cache-syslog`.
> fix(ci): make `acceptance-log-cache-syslog` run with a `metricsforwarder` sending metrics to the `loggr-syslog-agent`

- jobs/operator/spec
- operations/connect_to_postgres_with_certs.yml
- operations/disable-postgres-tls-config.yml
- templates/app-autoscaler.yml
The table `appinstancemetrics` got deleted with #2983, which makes references like `instancemetrics_db` stale.
Cleanup leftovers of `instancemetrics_db`
> fix(metrics-architecture): remove configuration referencing the dead table `appinstancemetrics`

- spec/jobs/golangapiserver/apiserver_spec.rb
- spec/jobs/metricsforwarder/metricsforwarder_spec.rb
- spec/jobs/operator/operator_spec.rb
- spec/jobs/scalingengine/scalingengine_spec.rb
- spec/jobs/scheduler/scheduler_spec.rb
By accident, the template tests of `metricsforwarder` got deleted by this change here: https://github.com/cloudfoundry/app-autoscaler-release/pull/2983/files#diff-8e5aca74dd557bdbb148f95e8ccec2a2b68b7f654ed055038fd14dec4d0eadbc. 
Restore the deleted test.
> fix(tests): restore `metricsforwarder` template test

- templates/app-autoscaler.yml
which was only used to sign the certificate `loggregator_agent_metrics_tls` which was removed by https://github.com/cloudfoundry/app-autoscaler-release/commit/3012a3e3a3958ab33facff60012300eddbc1296f#diff-276a5bf9491a6514a7792457803f74994a60f5cdc811948a3e6d555d4b43ffae
> chore(template): Remove unused `metric_scraper_ca`

- src/autoscaler/go.mod
- src/autoscaler/go.sum
This change bumps https://github.com/cloudfoundry/clock to the latest version by the time this PR was created.
> Bump `code.cloudfoundry.org/clock`

- .github/workflows/java-ci-lint.yaml
- src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManager.java
- style-guide/google-format-ci-v0.1.sh
With the update to JDK21 the Google Java Formatter was throwing following exception
``` https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/10076579459/job/27857239602?pr=3099
100 3309k  100 3309k    0     0  4753k      0 --:--:-- --:--:-- --:--:-- 77.7M
./src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestControllerCreateScheduleAndNofifyScalingEngineTest.java: error: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
at com.google.googlejavaformat.java.RemoveUnusedImports.getSimpleName(RemoveUnusedImports.java:263)
at …
```
> chore(deps) Bump Google Java Formatter to 1.22.0

- packages/eventgenerator/spec
- src/autoscaler/envelopeprocessor/envelope_processor.go
- src/autoscaler/envelopeprocessor/envelopeprocessor_test.go
- src/autoscaler/eventgenerator/metric/fetcher.go
- src/autoscaler/eventgenerator/metric/fetcher_test.go
- src/autoscaler/go.mod
- src/autoscaler/go.sum
The `dario.cat/mergo` library is being used to copy attributes between flat structs of the same type. However, this functionality is simple enough to implement directly, making the dependency unnecessary.
* Implement a custom function to copy a specific set of attributes from one struct to another.
* Remove the `dario.cat/mergo` dependency from the project.
> chore(dependencies): replace `"dario.cat/mergo` with a custom implementation

- ci/autoscaler/pipeline.yml
- ci/autoscaler/tasks/update-sdk/download_java.sh
- ci/autoscaler/tasks/update-sdk/update_java_package.sh
- ci/autoscaler/tasks/update-sdk/update_package.sh
This PR fixes  [update-java](https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release-fix-update-java-job/jobs/update-java/) CI Job which was somehow broken as apart of [PR#3087 ](https://github.com/cloudfoundry/app-autoscaler-release/pull/3087) ( change from java-bosh-release to Sapmachine JDK 21)
The jobs updates the JDK 21 LTS versions only.
Test PR # https://github.com/cloudfoundry/app-autoscaler-release/pull/3106 (should not be merged)
> chor(deps) Automate Java Package Version Update

- devbox.json
- devbox.lock
On starting the devbox all CF plugins were installed, regardless if
already installed or not, wasting time and screenspace.
Check if already installed (comparing the checksums) before installing.
> feat(devbox): Only install plugins if needed

- Makefile
- ci/autoscaler/scripts/common.sh
- ci/autoscaler/scripts/deploy-apps.sh
- ci/dockerfiles/autoscaler-tools/Dockerfile
- src/autoscaler/.gitignore
- src/autoscaler/Makefile
- src/autoscaler/example.mtaext
- src/autoscaler/metricsforwarder/Makefile
- src/autoscaler/mta.yaml
As part of our strategic move away from BOSH releases, we are initiating the transition of the MetricsForwarder Cloud Foundry Proof of Concept (POC) to utilize the MultiApps Controller. 
**Reduced Dependency:** This transition will gradually eliminate our reliance on existing VMs for fetching MetricsForwarder configurations.
**Enhanced Configuration Management:** By implementing MultiTarget Application (MTA) and MTA extension files, we establish a new configuration structure. This approach will eventually replace the BOSH job spec file configuration.
**Future-Proofing:** This change sets the foundation for further improvements and easier integration with other SAP Cloud Platform services.
**Test the new deployment process using the MultiApps Controller:** Replace `cf push` deployment with …
> poc(metricsforwarder): Use multiapps deploy to run metricsforwarder on cf

- .github/workflows/asdf2devbox.yaml
- devbox.json
- devbox.lock
- scripts/asdf2devbox.py
As the Nix package name contains the Java major version, the translation
needs to be updated now that we have switched to version 21
Just a static string change. Parsing it from the version number would be
possible, but as it is a LTS release the next update should be in the
far future.
> chore(asdf2devbox): Switch to Java 21

- ci/autoscaler/pipeline.yml
- ci/autoscaler/scripts/deploy-autoscaler.sh
- ci/autoscaler/set-pipeline.sh
- operations/use-cf-services.yml
- src/autoscaler/metricsforwarder/Makefile
This PR allows the PostgreSQL port to be set dynamically when accessed through the TCP route. This change enables us to run multiple Cloud Foundry (CF) workflows simultaneously, with each workflow connecting to a different PostgreSQL instance.
Modified TCP route to use dynamic ports matching PR number
Updated PostgreSQL connection on metriscforwarder cf app
WORKING BUILD: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release-autoscaler-775-dynamic-postgres-tcp-port/jobs/acceptance-log-cache-syslog-cf/builds/6
> Sets postgres port to current pr number if open pr exists

- src/autoscaler/metricsforwarder/manager/policyManager.go
- src/autoscaler/metricsforwarder/manager/policyManager_test.go
If an app was bound with a policy using custom metrics, even after the
policy being removed the app was still allowed to submit the custom
metrics previously used.
Correctly clear the entry in the cache if the policy was removed.
> fix(metricsforwarder): Clear allowed metrics cache once policy is removed.

- ci/autoscaler/pipeline.yml
[set-pipeline](https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/set-pipeline/builds/557) task does not have a variable required to run [cf acceptance tests](https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-log-cache-syslog-cf/builds/105)
Add missing variable to pipeline
> Adds missing pr variable to set-pipeline job

- src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
- src/autoscaler/db/sqldb/sqldb_suite_test.go
The ScalingEngineSqldb tests had become flaky
A well-meaning but harmfull test cleanup function was removed.
> fix(test): Fix `scalingengine_sqldb_test.go`

- src/autoscaler/build-extension-file.sh
The pipeline is currently failing:
https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-log-cache-syslog-cf/builds/118
The PR number in the build extension file is not required, default port 5432 will be assigned to the autoscaler Postgres TCP route when not available.
Removing this check would allow the pipeline to run for the concourse branch in main and for PRs
> Remove PR_NUMBER check from build-extension-file.sh in autoscaler module

- ci/infrastructure/pipeline.yml
The app-autoscaler-release should be able to run on foundations with only the Cloud Controller v3 API available.
Disable the v2 API.
- Might break stuff.
- `add-cflinuxfs4.yml` is deprecated and a no-op as `cflinuxfs4` is the default stack.
> chore(ci): Disable Cloud Controller v2 API in CI

- packages/golangapiserver/spec
- src/autoscaler/api/config/config.go
- src/autoscaler/go.mod
- src/autoscaler/go.sum
During a previous PR an outdated library was unintentionally referenced,
when the standard libray already provides the functionality.
Remove the usage of the library and use the standard library's
functionality.
> chore(deps): Remove unintentional usage of `gopkg.in/errgo.v2`

- src/acceptance/api/api_test.go
- src/acceptance/helpers/helpers.go
- src/autoscaler/api/publicapiserver/public_api_server.go
- src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
- src/autoscaler/integration/integration_golangapi_scalingengine_test.go
- src/autoscaler/routes/routes.go
It was possible to get information for a currently unbound app from the
API server
Check if the app is currently bound to the service on all routes.
> fix(apiserver): Check that app is bound on API routes

- src/autoscaler/mta.tpl.yaml
• Updated Module Requirements: Added app-autoscaler-dynatrace to the list of required modules.                                                                                                
• New Resource Definition: Defined a new resource app-autoscaler-dynatrace with type org.cloudfoundry.existing-service, marked as inactive and optional.
> Adds dynotrace service

- ci/autoscaler/scripts/deploy-autoscaler.sh
- operations/use-cf-services.yml
- src/autoscaler/build-extension-file.sh
- src/autoscaler/metricsforwarder/security-group.json
This pull request includes several changes to the autoscaler deployment scripts and configuration files to enhance the handling of the PostgreSQL connection which produces flaky tests when running acceptance test.
Enhancements to deployment scripts:
* [`ci/autoscaler/scripts/deploy-autoscaler.sh`](diffhunk://#diff-eb92f3568762003dbdddd247a28376d37d1d2177c1cc1f106180a0d8c0f92711R146-R148): Updated the `deploy` function to retrieve the PostgreSQL IP address and set it in CredHub.
Improvements to extension file handling:
* [`src/autoscaler/build-extension-file.sh`](diffhunk://#diff-8e3987a2578d4a70ff3e420127a452231d5f76e322f6baaadecd612a97932247L19-R22): Added the PostgreSQL IP to the extension file template and adjusted the URI generation to use the PostgreSQL IP if available. …
> Use postgres IP instead of TCP route when deploying apps

- ci/autoscaler/pipeline.yml
This pull request includes a small change to the `ci/autoscaler/pipeline.yml` file. The change adds a new job to the list of passed jobs in the pipeline configuration.
* [`ci/autoscaler/pipeline.yml`](diffhunk://#diff-10ff83017bf5f3630e6c372c3aa8dc981a23f71cdc48c725cd17509d8d757a03R455): Added `acceptance-log-cache-syslog-cf` to the list of passed jobs.
> Adds acceptance-log-cache-syslog-cf job as dependenct to release autoscaler

- src/autoscaler/api/db/servicebroker.db.changelog.yaml
- templates/app-autoscaler.yml
```
Starting Liquibase at 17:44:58 using Java 21.0.5 (version 4.29.2 #3683 built at 2024-08-29 16:45+0000)
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout | Running Changeset: var/vcap/packages/golangapiserver/servicebroker.db.changelog.yaml::5::Arsalan
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout |
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout | UPDATE SUMMARY
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout | Run:                          0
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout | Previously run:               4
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout | Filtered out:                 0
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: stdout | -------------------------------
apiserver/bd8aa6fb-3e0f-4d22-b9a6-df96ff7a62b2: …
```
> fix-> remove contrainst not null

- operations/external-db.yml
The v14.4.0 release of autoscaler introduces a db named `binding_db`, if you are using an external db, like RDS, and the ops file in `operations/external-db.yml` the templating errors out during deployment with:
```
Task 628502 | 15:28:11 | Error: Unable to render instance groups for deployment. Errors are:
- Unable to render jobs for instance group 'metricsforwarder'. Errors are:
- Unable to render templates for job 'metricsforwarder'. Errors are:
- Error filling in template 'metricsforwarder.yml.erb' (line 9: Can't find property '["autoscaler.binding_db.port"]')
```
By adding `binding_db` to the `external-db.yml` ops file, there is no longer a bosh templating error when not using the built in postgres instance.
> Adding binding_db to external-db.yml ops file

- src/autoscaler/api/broker/broker_test.go
- src/autoscaler/db/sqldb/binding_sqldb.go
- src/autoscaler/db/sqldb/binding_sqldb_test.go
- src/autoscaler/db/sqldb/sqldb_suite_test.go
**Problem**
The apiserver throws type conversion error if the custom metric strategy is defined as null or empty in the existing binding table.
**FIX**
Allow empty/null values for custom metrics strategy in the binding.
> fix(apiserver) Handle NPE for Custom Metrics Strategy

- operations/cf-mysql-db.yml
This PR add binding database connection info for mySQL database via the operation files. The database is used in the metricsForwarder component
> Fix(database) Add missing binding db connection details for mysql database

- src/acceptance/broker/broker_test.go
- src/autoscaler/api/broker/broker.go
- src/autoscaler/api/brokerserver/broker_handler_test.go
- src/autoscaler/models/binding_configs.go
**Problem**
The behavior of instance binding parameters was altered in [PR#3211](https://github.com/cloudfoundry/app-autoscaler-release/pull/3211). Specifically, the binding configuration object was always included, even when the binding was created with a policy instead of the configuration object.
**Fix**
Restore the previous behavior in the acceptance test. The endpoint `GET /v3/service_credential_bindings/:guid/parameters `should return the exact parameters that were provided during the binding process.
> Fix(Broker): Return the Same Instance Binding Parameters As Given In Binding Process

- Makefile
This pull request includes a change to the `Makefile` to ensure that the `integration` target runs the `generate-openapi-generated-clients-and-servers` task before building, initializing the database, and testing certificates.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L221-R221): Modified the `integration` target to include `generate-openapi-generated-clients-and-servers` as a prerequisite task.
> Add generate-openapi-generated-clients-and-servers as a dependency for the integration target in Makefile

- .github/workflows/acceptance_tests_reusable.yaml
Failing acceptance_tests jobs did not actually prevent the workflow from suceeding
remove continue-on-error from acceptance tests workflow
> chore(ci): remove continue-on-error from acceptance tests workflow

- src/autoscaler/eventgenerator/metric/fetcher.go
Some `Info` log statements are filling up our log files.
don't log all 1k received envelopes but just the number of envelopes
> chore(logcache fetcher): only log number of received envelopes

- src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml
The index `index_app_metrics` was not created on PostgreSQL leading to bad performance.
The correct `DBMS/shortname` for PostgreSQL is  `postgresql` as [documented](https://docs.liquibase.com/start/tutorials/home.html)
> fix(db): set correct dbms short name `postgresql`

- ci/autoscaler/scripts/deploy-autoscaler.sh
- jobs/scalingengine/spec
- jobs/scalingengine/templates/scalingengine.yml.erb
- operations/use-cf-services.yml
- packages/scalingengine/spec
- spec/jobs/scalingengine/scalingengine_spec.rb
- src/autoscaler/api/brokerserver/broker_server.go
- src/autoscaler/api/brokerserver/broker_server_suite_test.go
- src/autoscaler/api/cmd/api/api_test.go
- src/autoscaler/api/cmd/api/main.go
- src/autoscaler/api/publicapiserver/public_api_server.go
- src/autoscaler/api/publicapiserver/public_api_server_test.go
- src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
- src/autoscaler/build-extension-file.sh
- src/autoscaler/generate-fakes.go
- src/autoscaler/helpers/auth/xfcc_auth.go
- src/autoscaler/helpers/auth/xfcc_auth_test.go
- src/autoscaler/helpers/http_server.go
- src/autoscaler/models/api.go
- src/autoscaler/routes/routes.go
- src/autoscaler/routes/routes_test.go
- src/autoscaler/scalingengine/cmd/scalingengine/main.go
- src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
- src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
- src/autoscaler/scalingengine/config/config.go
- src/autoscaler/scalingengine/config/config_test.go
- src/autoscaler/scalingengine/config/testdata/valid.yml
- src/autoscaler/scalingengine/server/server.go
- src/autoscaler/scalingengine/server/server_test.go
- src/autoscaler/testhelpers/certs.go
This pull request adds a new xfcc unified endpoint to the scaling engine that will be consumed by the API component once it is deployed as a Cloud Foundry application.
includes several changes to the `deploy-autoscaler.sh` script, configuration files, and tests related to the autoscaler deployment and CF server configurations. The most important changes include refactoring the `deploy-autoscaler.sh` script for better readability and maintainability, adding new CF server configurations, and updating tests to reflect these changes.
* Refactored the `deploy-autoscaler.sh`. [[1]](diffhunk://#diff-eb92f3568762003dbdddd247a28376d37d1d2177c1cc1f106180a0d8c0f92711L12-R34) [[2]](diffhunk://#diff-eb92f3568762003dbdddd247a28376d37d1d2177c1cc1f106180a0d8c0f92711R63-R113)
* Added new properties for CF …
> (feat) Add XFCC authenticated scaling engine endpoint

- .github/workflows/acceptance_tests_reusable.yaml
Due to https://github.com/actions/runner/issues/2566 skipped "Result" jobs are considered successful checks. This breaks our PR validation.
Introduce an ugly workaround: A new Result job that will be always skipped except when a required job fails, in which case it also fails.
We could probably improve the naming and not call it "Result" but "Acceptance test failure blocker" or something to that end, but as the branch protection is controlled via another repo, let's keep it for now until we have validated everything to work as intended.
> fix(ci): workaround skipped jobs being considered successful

- devbox.json
- nix/flake.lock
- nix/flake.nix
Using the main flake for the devbox is slow as the nix commands executed via devbox have to copy around the main repo:
```
$ nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' search 'path:/home/mysuser/app-autoscaler-release#cloud-mta-build-tool' ^ --json
copying '/home/myuser/as/app-autoscaler-release'
```
Use a special nix flake in a subdirectory where copying it is fast.
> chore(devbox): Introduce special nix flake for devbox

- .tool-versions
- Makefile
- devbox.json
- devbox.lock
- flake.nix
- renovate.json
- src/autoscaler/cf/client.go
- src/autoscaler/cf/mocks/mocks.go
- src/autoscaler/cf/mocks/mocks_test.go
- src/autoscaler/cf/oauth.go
- src/autoscaler/cf/oauth_test.go
- src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
- src/autoscaler/integration/integration_golangapi_scalingengine_test.go
- src/autoscaler/integration/integration_golangapi_scheduler_test.go
- src/autoscaler/integration/integration_suite_test.go
UAA has deprecated the `check_token` endpoint and recommends using the
`introspect` endpoint:
https://docs.cloudfoundry.org/api/uaa/version/77.19.0/index.html#check-token
- **chore(oauth): Replace deprecated `check_token` usage with `introspect`**
- **chore(devbox): Remove superfluous `google-cloud-sdk`**
There's no need for  `google-cloud-sdk` in this repo, accessing the CI environment cloud provider this should happen through the `app-runtime-interface-wg` repo.
> chore(oauth): Replace deprecated `check_token` usage with `introspect`

- src/autoscaler/api/broker/broker_test.go
- src/autoscaler/models/binding_configs.go
- src/autoscaler/models/binding_configs_test.go
**Fix**
Use Correct Type upon retrieval of binding
> Use Correct Type Upon Binding Retrieval

- .github/workflows/renovate_config_validation.yaml
- renovate.json
Updating the OpenTelemetry SDK can break consumers of OpenTelemetry
tracing data such as Dynatrace if they do not support the SDK version.
For now disable updates through Renovate.
As soon as the supported versions are documented we can addd some
automation back to update to the latest supported versions.
> chore(renovate): Disable OpenTelementry SDK updates

- src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml
Under certain cases, it may happen that pgaudit on older PostgreSQL-versions gets an internal error when creating the app-metrics-index for the eventgenerator. This change checks, if it is actually needed in advance. This makes a manual fix easy by just creating the index e.g. with psql.
> Check – before creating an index for the app-metrics – if it is already there.

- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/dao/ActiveScheduleDaoImplFailureTest.java
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleJobTest.java
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestControllerTest.java
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleSyncRestControllerTest.java
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleJobManagerTest.java
- src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManagerTest.java
```
Warning:  /__w/app-autoscaler-release/app-autoscaler-release/src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManagerTest.java:[94,4] org.springframework.boot.test.mock.mockito.SpyBean in org.springframework.boot.test.mock.mockito has been deprecated and marked for removal
```
Run [Replace `@MockBean` and `@SpyBean`
](https://docs.openrewrite.org/recipes/java/boot3/replacemockbeanandspybean) OpenRewrite recipe:
```
$ mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE -Drewrite.exportDatatables=true -Drewrite.activeRecipes=org.openrewrite.java.spring.boot3.ReplaceMockBeanAndSpyBean
...
Estimate time saved: 30m
```
> chore(scheduler): Replace deprectated Mockito annotations

- .gitignore
- src/autoscaler/api/publicapiserver/middleware_test.go
- src/autoscaler/api/publicapiserver/public_api_server_test.go
- src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
- src/autoscaler/helpers/httpclient.go
- Add `ginkgo.report` to .gitignore
- Introduce `GetTestHandler` and `CheckResponse` functions in middleware tests
- Remove duplicated test utility functions from `publicapiserver_suite_test.go`
- Add missing stub routes for eventgenerator
- Adjust logging in `TLSReloadTransport` to exclude request data
>  Fix failing case in publicapi test suite

- .github/workflows/openapi-specs-check.yaml
- Makefile
- devbox.json
- devbox.lock
- flake.nix
Redocly CLI is the recommended replacement for the deprecated swagger-cli package
See https://redocly.com/docs/cli/guides/migrate-from-swagger-cli
> feat: replace `swagger-cli` with `redocly` for OpenAPI validation

- .github/workflows/acceptance_tests_broker.yaml
- src/autoscaler/operator/applicationsyncer.go
- src/autoscaler/operator/applicationsyncer_test.go
We exit early rather than continuing over the rest of the list. This could cause a single continuous failure in the db to create a buildup of autoscaler policies without apps.
Continue instead.
Fixes: #837
Acceptance tests were retriggered by labeling.
Remove `labeled` trigger.
> fix(operator): continue deletion of non-existent application records on error

- .github/workflows/java-ci-lint.yaml
- devbox.json
- devbox.lock
- src/scheduler/Makefile
- Remove use of app autoscaler release 
- Add steps to install Devbox and make its shell environment available
- Add google-java-format to devbox
- Create new Makefile in src/scheduler for Java formatting and checking
>  Update GitHub Actions workflow and Devbox configuration for Java linting

- src/autoscaler/Makefile
- src/autoscaler/mta.tpl.yaml
If the default version of the Go toolchain in the Go buildpack was not sufficient for the code to compile, during staging a call to the internet would be made to download the appropriate version. This would fail in air gapped environments.
Set `GOTOOLCHAIN=local` and the appropriate `GOVERSION`
> fix(mta): Ensure apps can be staged in air gapped environments

- renovate.json
Now that Renovate supports `devbox` we need to disable the automatic update of Go here as well.
Disable `go` version updates in `devbox`.
> chore(renovate): disable Go version updates in devbox

- renovate.json
Previously we decided to not run renovate during office hours to reserve the limited GitHub actions runners capacity for our own PRs, which on the other hand makes our automated dependency updates slower and less reactive.
With the [enablement of GitHub Enterprise Cloud](https://cloudfoundry.slack.com/archives/C026XJGNC2U/p1739319963575719) we among other benefits get
> 50,000 GitHub Actions minutes per month  instead of 2,000
so we should be good to enable renovate PRs during office hours.
Remove `nonOfficeHours` preset.
> chore(renovate): Also run during office hours

- ci/autoscaler/pipeline.yml
- Added ENABLE_MTAR flag to app-autoscaler-ops-files-log-cache-syslog-cf
- Removed use-cf-services.yml and configure-cf-services.yml from the pipeline (they are added now by the deploy-release.sh script.
> Fix concourse pipeline

- .editorconfig
- ci/autoscaler/scripts/common.sh
When undeployment fails during the acceptance test teardown phase—specifically in the `autoscaler-cleanup` step—it can leave behind orphaned (zombie) orgs and spaces. These residual resources can clutter the environment and cause issues for subsequent test runs.
In [this workflow run](https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/13784567998/job/38553327654), the cleanup process did not successfully remove all resources.
This occurred in [PR #3629](https://github.com/cloudfoundry/app-autoscaler-release/pull/3629), where the test org and space were not cleaned up as expected.
Now `cf undeploy` fails gracefully
> (fix) Fix mtar cleanup for acceptance tests

- src/autoscaler/Makefile
Building autoscaler's executables requires clients and servers defined in the openapi-v3-specification. The lack of having defined this dependency in the Makefiles led to bugs like <https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/integration-tests/builds/2262#L68064499:229>.
> Add missing Make-dependency;

- src/autoscaler/api/cmd/api/api_test.go
- src/autoscaler/api/config/config.go
- src/autoscaler/api/default_config.json
- src/autoscaler/build-extension-file.sh
- src/autoscaler/integration/integration_golangapi_scheduler_test.go
- src/autoscaler/mta.tpl.yaml
This PR matches current vm name with mtar module vm name:
- Rename 'publicapiserver' module to 'apiserver'
- Add new dependencies to 'apiserver' module: 'publicapiserver-config', 'broker-catalog', and 'database'
- Include 'app-autoscaler-dynatrace' as a new dependency for 'apiserver' in mta.tpl.yaml
>  (feature): Refactor module names and update dependencies in autoscaler configs

- operations/add-postgres-variables.yml
This pull request updates the `operations/add-postgres-variables.yml` file to enhance security by increasing the key length for cryptographic operations. The key length is now explicitly set to 4096 bits in multiple sections of the file.
Security enhancements:
* Added `key_length: 4096` to the `options` section for the `postgresCA` variable to enforce a stronger cryptographic key length.
* Included `key_length: 4096` in the `options` section to ensure consistent key length for client and server authentication.
* Added `key_length: 4096` to the `options` section for the autoscaler Postgres service, further standardizing the key length across configurations.
> Increase key length to 4096 for Postgres-related SSL 

- ci/autoscaler/pipeline.yml
Problem
```
...
Will run 19 of 19 specs
Running in parallel across 3 processes
••••••••••••••••••make[1]: *** [Makefile:82: run-acceptance-tests] Terminated
make: *** [Makefile:442: acceptance-tests] Terminated
timeout exceeded
```
Affected Job: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-log-cache-syslog/builds/760#L68167d7b:30
> Increase timeout for concourse app task e.g app, broker api test suites

- ci/infrastructure/pipeline.yml
- ci/infrastructure/scripts/deploy-multiapps-controller.sh
* deploy service is too small to handle >1GB .MTAR files
* CF needs to be deployed first before deploying the multiapps controller
* scale up `deploy-service`
* require `deploy-cf` to be passed before deploying deploy service
Screenshot shows that `deploy-cf` must pass:
Screenshot shows that scaling up works:
> chore(ci): scale up deploy-service, require `deploy-cf` to be passed before deploying multiapps-controller

- .github/workflows/resume-ci-vms.yml
- .github/workflows/suspend-ci-vms.yml
- ci/autoscaler/pipeline.yml
- ci/autoscaler/scripts/deploy-autoscaler.sh
- ci/infrastructure/pipeline.yml
- ci/infrastructure/scripts/deploy-postgres.sh
- ci/operations/tag-vms-and-disks.yml
- renovate.json
The current hibernation #3856 does only hibernate those VMs that are tagged with `belongs-to: autoscaler`. The problem here is that the Bosh director and some more VMs aren't labelled because they are being set up by a reusable job, which does not offer the possibility via it's interface to add tagging. 
https://github.com/cloudfoundry/app-autoscaler-release/blob/18e3fb14deec1eb6908a5927ff93cea4bd9f0b68/ci/infrastructure/pipeline.yml#L131-L132
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/main/bbl-up/task.yml
* suspend/resume all VMs inside the `autoscaler` network to catch all VMs
* revert tagging logic introduced with #3854 
The resuming all VMs turned out to break the ingress traffic into the CF landscape. To be precise, suspending and resuming the load balancer's …
> chore(ci): hibernate all VMs inside the autoscaler network

- templates/app-autoscaler.yml
Due to https://github.com/cloudfoundry/uaa/issues/3333 UAA clients with secrets longer than 72 characters can no longer  be created.
Restrict length to 64 characters uniformly.
> Fix(Passwords) Reduce password length from 128 to 64

- .github/workflows/image.yaml
Our `autoscaler-tools` image build is broken since ages: 
Don't run the build in devbox, just install the `devbox` command to fix the workflow.
The trigger was broken, so we did not see the failures in any PRs touching the workflow.
> fix(ci): Fix image build

- .github/workflows/postgres.yaml
PostgreSQL 12 is end of life since [9 months](https://endoflife.date/postgresql) and we can save some GitHub Action workflow runs by removing the PostgreSQL 12 tests from the test matrix
Remove them from the matrix
Depends on https://github.com/cloudfoundry/community/pull/1303 to mergeable.
> chore(tests): remove PostgreSQL 12 from test matrix

- devbox.json
- devbox.lock
While building go programs via `make build_all`, following error occurs.
```
cgo-builtin-prolog:1:10: fatal error: 'stddef.h' file not found
1 | #include <stddef.h>
|          ^~~~~~~~~~
1 error generated.
```
Environment
- MacOS Tahoe 26.0.1
- nix --version `nix (Determinate Nix 3.11.2) 2.31.1`
- xcode-select -p `/nix/store/rhlyld20zdzdi5wghb4b12gw52s9whr9-apple-sdk-11.3`
> Fix(chore): Go Modules Do Not Build because of Missing C Header File stddef.h

- ci/operations/scale_out_cf_for_app-autoscaler.yaml
If many PRs are in in flight apps fail to start with
`insufficient resources: memory`
Overcommit memory. This should work as our apps use way less memory than
their quota, e.g.
```
$ cf app operator
Showing health and status for app operator in org autoscaler-mta-3951 /
space autoscaler-mta-3951 as admin...
name:              operator
requested state:   started
routes:
autoscaler-mta-3951-operator.autoscaler.app-runtime-interfaces.ci.cloudfoundry.org
last uploaded:     Tue 30 Sep 11:12:02 CEST 2025
stack:             cflinuxfs4
buildpacks:
name           version   detect output   buildpack name
go_buildpack   1.10.38   go              go
type:           web
sidecars:
instances:      1/2
memory usage:   1024M
state     since                  cpu    memory        disk
logging …
```
> chore: Overcommit memory in CI CF env

- .github/workflows/image.yaml
The wrong Go version is packaged in our CI image: https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/18191694489/job/51787975268
```
Run version=$(devbox info go | head --lines=1 | cut --field=2 --delimiter=" ")
Go version from devbox: '1.25.0'
```
but actually Go 1.24.3 should be in the image.
Parse the `devbox.json` to get the Go version: https://github.com/cloudfoundry/app-autoscaler-release/actions/runs/18338845499/job/52229114616?pr=3959
```
Run jannekem/run-python-script-action@bbfca66c612a28f3eeca0ae40e1f810265e2ea68
/usr/bin/python /tmp/tmp-41095-Rxpi4UaJ1oc0-.py
Go version from devbox.json: '1.24.3'
```
[Reached out to devbox discord](https://discord.com/channels/903306922852245526/1009933892385517619/1425405295793934347) to understand if this a bug in `devbox …
> chore: fix Go version determination to use devbox.json
