cloudfoundry/app-autoscaler-release

jobs/apiserver/spec
jobs/apiserver/templates/apiserver.erb
packages/common/packaging
packages/common/spec
src/common/utils.sh

Added common package for PID utils and drains.

Added common package for PID utils

---

packages/db/pre_packaging
packages/db/spec
src/common/pre-packaging-helper.sh

1) Added helper script for maven and java setup.
2) Used setup helper in DB packaging

Moved Java and Maven set up to common package

---

example/bosh-lite-manifest-template.yml
example/cloud-config.yml
example/properties.yml
jobs/scheduler/monit
jobs/scheduler/spec
jobs/scheduler/templates/application.properties.erb
jobs/scheduler/templates/pre-start.erb
jobs/scheduler/templates/scheduler.erb
packages/scheduler/packaging
packages/scheduler/pre_packaging
packages/scheduler/spec

Added scheduler in app-autoscaler bosh release

Added scheduler in app-autoscaler bosh release

---

example/bosh-lite-manifest-template.yml
example/cloud-config.yml
example/properties.yml
jobs/apiserver/templates/apiserver.erb
jobs/servicebroker/monit
jobs/servicebroker/spec
jobs/servicebroker/templates/config.json.erb
jobs/servicebroker/templates/pre-start.erb
jobs/servicebroker/templates/servicebroker.erb
packages/apiserver/pre_packaging
packages/apiserver/spec
packages/db/pre_packaging
packages/db/spec
packages/scheduler/pre_packaging
packages/scheduler/spec
packages/servicebroker/packaging
packages/servicebroker/pre_packaging
packages/servicebroker/spec
src/common/java-helper.sh
src/common/node-helper.sh
src/common/pre-packaging-helper.sh

Added service-broker in app-autoscaler bosh release

Added service-broker in app-autoscaler bosh release

---

example/bosh-lite-manifest-template.yml
example/cloud-config.yml
example/properties.yml
jobs/apiserver/spec
jobs/metricscollector/monit
jobs/metricscollector/spec
jobs/metricscollector/templates/metricscollector.yml.erb
jobs/metricscollector/templates/metricscollector_ctl
jobs/metricscollector/templates/pre-start.erb
jobs/scheduler/spec
jobs/servicebroker/spec
packages/golang1.7/packaging
packages/golang1.7/spec
packages/metricscollector/packaging
packages/metricscollector/spec

metrics collector bosh release

---

example/bosh-lite-manifest-template.yml
example/cloud-config.yml
example/properties.yml
jobs/pruner/monit
jobs/pruner/spec
jobs/pruner/templates/pruner.yml.erb
jobs/pruner/templates/pruner_ctl
packages/pruner/packaging
packages/pruner/spec

BOSH deploy dbpruner

---

example/property-overrides.yml
jobs/scheduler/spec
jobs/scheduler/templates/application.properties.erb

https://www.pivotaltracker.com/story/show/139259235

139259235 : Moved job properties nested under scaling engine from scheduler properties

---

src/acceptance/assets/file/policy/all.json
src/acceptance/assets/file/policy/invalid.json

Please note these properties are relevant once the PR https://github.com/cloudfoundry-incubator/app-autoscaler-release/pull/18 is merged.

140112487: Change property name to memoryused in acceptance test policy json files

---

README.md
example/bosh-lite-manifest-template.yml
example/dbstubs/db-stub-external-multi.yml
example/dbstubs/db-stub-external.yml
example/property-overrides.yml
jobs/apiserver/spec
jobs/apiserver/templates/config.json.erb
jobs/apiserver/templates/pre-start.erb
jobs/eventgenerator/spec
jobs/eventgenerator/templates/eventgenerator.yml.erb
jobs/eventgenerator/templates/pre-start.erb
jobs/metricscollector/spec
jobs/metricscollector/templates/metricscollector.yml.erb
jobs/metricscollector/templates/pre-start.erb
jobs/pruner/spec
jobs/pruner/templates/pruner.yml.erb
jobs/scalingengine/spec
jobs/scalingengine/templates/pre-start.erb
jobs/scalingengine/templates/scalingengine.yml.erb
jobs/scheduler/spec
jobs/scheduler/templates/application.properties.erb
jobs/scheduler/templates/pre-start.erb
jobs/servicebroker/spec
jobs/servicebroker/templates/config.json.erb
jobs/servicebroker/templates/pre-start.erb
scripts/generate-bosh-lite-manifest

1. Default DB injected into deployment. 
2. Refactored so that each service can point to its own DB server.
3. Added example db stubs.

[#138710007] default postgresql db details injected into deployment 

---

jobs/apiserver/templates/apiserver.erb
jobs/eventgenerator/templates/eventgenerator_ctl
jobs/metricscollector/templates/metricscollector_ctl
jobs/pruner/templates/pruner_ctl
jobs/scalingengine/templates/scalingengine_ctl
jobs/scheduler/templates/scheduler.erb
jobs/servicebroker/templates/servicebroker.erb

- Removed the -x from the ctl scripts.
- Added missing -e in some of the ctl scripts.

#140978589 : Remove the -x from all the ctl scripts

---

src/acceptance/app/app_suite_test.go
src/acceptance/app/dynamic_policy_test.go
src/acceptance/assets/app/nodeApp/package.json
src/acceptance/assets/app/nodeApp/test.js
src/acceptance/example_config/example.json

[#141357881]
- refactor/fix node.js test app
- adjust threshold and time

fix dynamic scaling acceptance test

---

example/property-overrides.yml
jobs/servicebroker/spec
jobs/servicebroker/templates/catalog.json.erb
jobs/servicebroker/templates/config.json.erb
jobs/servicebroker/templates/servicebroker.erb

[#142380439]
1. Made Service Catalog properties configurable.
2. Bumped up app-autoscaler

Bump src/app-autoscaler

---

src/acceptance/app/app_suite_test.go
src/acceptance/app/recurring_schedule_policy_test.go
src/acceptance/app/specificdate_schedule_policy_test.go

generate scheduled policy in acceptance test

---

example/property-overrides.yml
jobs/apiserver/spec
jobs/apiserver/templates/config.json.erb
jobs/apiserver/templates/scalingengine_ca.crt.erb
jobs/apiserver/templates/scalingengine_client.crt.erb
jobs/apiserver/templates/scalingengine_client.key.erb
jobs/metricscollector/spec
jobs/metricscollector/templates/metricscollector.yml.erb
jobs/scheduler/spec
jobs/scheduler/templates/application.properties.erb
packages/metricscollector/spec
src/acceptance/app/app_suite_test.go
src/acceptance/app/dynamic_policy_test.go
src/acceptance/app/recurring_schedule_policy_test.go
src/acceptance/app/specificdate_schedule_policy_test.go
src/acceptance/assets/app/nodeApp/package.json
src/acceptance/config/config.go
templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

- bump latest app-autoscaler code
- bosh release code change accordingly
- add acceptance test for memoryutil based scaling
- refactor other acceptance tests

enable memoryutil based scaling

---

templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

- #59 
- https://github.com/cloudfoundry-incubator/app-autoscaler-release/commit/7c8dc54c18cf8e074f4e08118aa6a2f2943f6007

Postgres Url Version Added

---

example/property-overrides.yml
jobs/apiserver/spec
jobs/apiserver/templates/config.json.erb
jobs/apiserver/templates/metricscollector_ca.crt.erb
jobs/apiserver/templates/metricscollector_client.crt.erb
jobs/apiserver/templates/metricscollector_client.key.erb

Add metricsCollector config to apiServer deployment.

---

src/acceptance/broker/broker_test.go

acceptance for bind without policy in broker

---

example/property-overrides.yml
jobs/metricscollector/spec
jobs/metricscollector/templates/metricscollector.yml.erb

- change poll_interval to collect_interval
- change the refresh_interval to 30s to speed up the test

sync  metricscollector config with latest

---

templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

consume consul from latest(270) cf-release

---

templates/app-autoscaler-deployment.yml

Added missing configuration for public api configuration in deployment type autoscaler manifest

#150472731: Added public api relevant configuration in deployment type manifest

---

src/acceptance/broker/broker_test.go

Fix service broker acceptance error

---

templates/app-autoscaler-deployment.yml

[#151116576]
fix issue: Deploy with cf-deployment error with "vm_type: default"

change vm_type from default to minimal

---

jobs/apiserver/templates/config.json.erb
templates/app-autoscaler-deployment.yml
templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

[#151240930]
1 Disable public api’s tls
2 Register public api to gorouter by nats

Register apiserver to gorouter

---

jobs/servicebroker/templates/config.json.erb
templates/app-autoscaler-deployment.yml
templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

[#151509412]
1 disable tls of servicebroker
2 register servicebroker to gorouter by nets

Register servicebroker to gorouter

---

example/dbstubs/db-stub-external-multi.yml
example/property-overrides.yml
jobs/metricscollector/spec
jobs/metricscollector/templates/metricscollector.yml.erb
packages/metricscollector/spec
templates/app-autoscaler-deployment.yml
templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

Bump up app-autoscaler, Enable Database lock

---

README.md
example/property-overrides.yml
jobs/apiserver/spec
jobs/apiserver/templates/config.json.erb
jobs/metricscollector/spec
jobs/metricscollector/templates/metricscollector.yml.erb
jobs/scalingengine/spec
jobs/scalingengine/templates/scalingengine.yml.erb
templates/app-autoscaler-deployment.yml
templates/bosh-lite-manifest-template-v1.yml
templates/bosh-lite-manifest-template-v2.yml

Bump up app-autoscaler

---

jobs/operator/spec
jobs/operator/templates/operator.yml.erb
jobs/scheduler/spec

remove consul lock relevant code. #171

---

src/acceptance/api/api_suite_test.go
src/acceptance/api/api_test.go
templates/app-autoscaler-deployment.yml

Sorry,  made a typo on app-autoscaler-deployment.yml  in last PR.  The fix is validated on bosh-lite again.

bug fix on app-autoscaler-deployment.yml

---

src/changeloglockcleaner/sqldb/changelogdb.go

remove dburl with password from log print

---

jobs/scheduler/templates/install_crt_truststore.erb

Fix certificate rotation for the scheduler component

---

jobs/golangapiserver/spec

change the autoscaler version to 3.0.1 in golangapiserver

---

jobs/scheduler/templates/application.properties.erb

The bump to Spring Boot 2.1 introduced some changes to the structure of the application*.properties files

Update generated properties for spring-boot 2.1 and above

---

.github/workflows/bosh.yaml
.github/workflows/mysql.yaml
.github/workflows/postgres.yaml
config/blobs.yml
config/final.yml
packages/db/spec
packages/golang/packaging
packages/golang/spec
packages/java/packaging
packages/java/spec
packages/maven/packaging
packages/maven/spec
packages/scheduler/spec
src/common/java-helper.sh

Updated blob versions to the latest available (latest LTS for Java)

Switch to use new blobstore

---

src/acceptance/bin/test

Remove ginkgo installation

---

src/changelog/display/output.go
src/changelog/main.go

Query submodule to determine the complete list of PRs for the changlog

---

jobs/eventgenerator/spec
jobs/golangapiserver/spec
jobs/metricsforwarder/spec
jobs/metricsgateway/spec
jobs/metricsserver/spec
jobs/operator/spec
jobs/scalingengine/spec

Create hotfix release v3.0.6.1+sap

Update default max and idle db connections

---

jobs/eventgenerator/templates/eventgenerator.yml.erb
jobs/golangapiserver/templates/apiserver.yml.erb
jobs/metricsforwarder/templates/metricsforwarder.yml.erb
jobs/metricsgateway/templates/metricsgateway.yml.erb
jobs/metricsserver/templates/metricsserver.yml.erb
jobs/operator/templates/operator.yml.erb
jobs/scalingengine/templates/scalingengine.yml.erb

url_encode  credentials in PostgreSQL URLs

url_encode credentials in PostgreSQL URLs

---

.github/workflows/golangci-lint.yaml
Makefile

- started new makefile for linting

Added makefile for linting

---

jobs/golangapiserver/spec
jobs/golangapiserver/templates/apiserver.yml.erb
spec/jobs/golangapiserver/apiserver_spec.rb

https://bosh.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-pr/builds/169

Add quota managment configuration

---

jobs/golangapiserver/spec
jobs/golangapiserver/templates/apiserver.yml.erb
spec/jobs/golangapiserver/apiserver_spec.rb

Failing on https://bosh.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-pr/builds/168

Add plan check configuration

---

jobs/golangapiserver/spec
jobs/golangapiserver/templates/apiserver.yml.erb
jobs/golangapiserver/templates/storedprocedure_db_ca.crt.erb
jobs/metricsforwarder/spec
jobs/metricsforwarder/templates/metricsforwarder.yml.erb
jobs/metricsforwarder/templates/storedprocedure_db_ca.crt.erb
packages/custommetricscredhelperplugin/spec
packages/golangapiserver/spec
packages/metricsforwarder/spec
spec/jobs/golangapiserver/apiserver_spec.rb
spec/jobs/metricsforwarder/metricsforwarder_spec.rb

This depends on #https://github.com/cloudfoundry/app-autoscaler/pull/794

Added templating for stored procedure

---

.github/workflows/dependabot_update.yaml

Added a GHA to update the srcs on a dependabot PR

Update the src lists in a dependabot PR

---

scripts/update
src/acceptance/.gitignore

Signed-off-by: Jörg Weisbarth <joerg.weisbarth@sap.com>

Vendor files for the acceptance tests;

---

src/changelog/main.go

release number 3.6.1 doesn't appear to be in the graphql api, this change will handle this scenario and display no PRs, rather than all PRs.

Fix changelog generation when previous release cannot be found

---

Makefile

Workaround for issue https://github.com/golang/go/issues/49138

Patch for bug in golang with montery

---

jobs/golangapiserver/templates/apiserver.yml.erb
spec/jobs/golangapiserver/apiserver_spec.rb

- Selects role with storeprocedure_db by default instead of default
- Refactor apiserver template and spec

Uses storedb tag correctly to assign db credentials

---

templates/app-autoscaler-deployment.yml

Which needs a bump for `routing-release` and `bpm` as an addon for it.
Closes #253

Update manifest template to bionic

---

.envrc
src/autoscaler/Makefile

asdf should find the right config better on its own.
Signed-off-by: Jörg Weisbarth <joerg.weisbarth@sap.com>

Remove problematic content of .envrc

---

.envrc
src/autoscaler/integration/integration_suite_test.go
src/autoscaler/metricsserver/collector/collector_test.go

recreated based on https://github.com/cloudfoundry/app-autoscaler-release/pull/516

Adding descriptions to tests

---

.github/workflows/java-ci-lint.yaml
Makefile
README.md
src/scheduler/pom.xml
src/scheduler/spotbugs-security-exclude.xml
src/scheduler/spotbugs-security-include.xml

with [OWASP Find Security Bugs](https://github.com/find-sec-bugs/find-sec-bugs) for the Java code.
Results at https://sonarcloud.io/project/overview?id=app-autoscaler-release

Setting up sonarcloud.io

---

src/changelog/github/github.go
src/changelog/main.go

Get latest commit from local repository as this has the most recent state we should work with.

Fix fetching of latest commit

---

src/changelog/github/github.go
src/changelog/main.go

… and do some small refactorings.

Adding cli options to changelog generation

---

Makefile
src/autoscaler/Makefile
src/autoscaler/db/sqldb/scalingengine_sqldb.go
src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
src/autoscaler/db/sqldb/sqldb_suite_test.go

- working on scalingengine_sqldb_test
- Fixed up the scalingEngine db tests to work in parrallel

Part 3: Fixed the scaling engine tests to work in parrallel

---

src/acceptance/helpers/helpers.go

- Adding assert check for empty org in acceptance tests
- removed space to get concourse to kick off

Adding assert check for empty org in acceptance tests

---

.github/test/closed_event.json
.github/workflows/acceptance_tests_close.yaml
.github/workflows/acceptance_tests_close_merge.yaml

- Adding closed PR cleanup as a secondary cleanup to make sure its cleaned up
- Added github closed catch for cleaning up on closed but not merged PR's

Cleanup acceptance tests after closed PR

---

ci/autoscaler/pipeline.yml

Add log-cache enabled job in release pipeline at https://bosh.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release

Log cache ci

---

.tool-versions
ci/autoscaler/tasks/update-sdk/vendor_package.sh

fix broken path for dependencies updates
[https://bosh.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/update-golang/builds/53#L62be70c6:2](https://bosh.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/update-golang/builds/53#L62be70c6:2)

Fix ci dependencies orphaned paths

---

.github/workflows/install_cli.sh

- adding sha256 checks to the tools
- adding sha 256 checks

Added sha checks for the installed cli tools in the acceptance test GHA

---

templates/app-autoscaler-deployment.yml

Bump postgres to version 31

---

.github/workflows/dependabot-auto-merge.yaml

by switching to a different action

Fix dependabot auto-merge

---

scripts/cleanup_closed_prs.sh
scripts/deploy_acceptance_app.sh
src/autoscaler/cf/app.go
src/autoscaler/cf/app_integration_test.go
src/autoscaler/cf/app_test.go
src/autoscaler/cf/client.go
src/autoscaler/cf/config.go
src/autoscaler/cf/testdata/app_processes.json
src/autoscaler/cf/testdata/test_app/.gitignore
src/autoscaler/cf/testdata/test_app/app.js
src/autoscaler/cf/testdata/test_app/deploy.sh
src/autoscaler/cf/testdata/test_app/manifest.yml
src/autoscaler/cf/testdata/test_app/package-lock.json
src/autoscaler/cf/testdata/test_app/package.json

- Addition of retries to the cf api client

Adding missing pagination to GET /v3/app/{guid}/processes

---

.github/workflows/dependabot-auto-merge.yaml

Fix dependabot auto-merge #3

---

templates/app-autoscaler-deployment.yml

This is an update from 9.6.10 to 11.1!

Bump PostgreSQL release to version 35

---

src/autoscaler/cf/retriever.go
src/autoscaler/cf/retriever_test.go

Fixes https://github.com/cloudfoundry/app-autoscaler-release/issues/814

Fix for connections not being reused if cf api returns a >=300 response

---

src/autoscaler/cf/service_instances.go
src/autoscaler/cf/service_instances_test.go
src/autoscaler/cf/service_plans.go
src/autoscaler/cf/testdata/service_instance.json
src/autoscaler/integration/integration_suite_test.go
src/autoscaler/testhelpers/mocks.go
src/autoscaler/testhelpers/mocks_test.go

- Removed Used/Dead code and pulled out get Instances
- Moving plans stuff out of the service_instance file
- simplify GetServiceInstance along with test

migrated `/v2/service_instances/:guid` to `/v3/service_instances/:guid`

---

Makefile
src/autoscaler/api/brokerserver/broker_handler.go
src/autoscaler/cf/client.go
src/autoscaler/cf/memoizer.go
src/autoscaler/cf/memoizer_test.go
src/autoscaler/cf/service_plans.go

- added mocks
- factored out the gets
- Refactored out the get inteface calls and added a memoiser

Added memoiser and refactored out Get instance calls

---

src/autoscaler/cf/service_instances.go
src/autoscaler/cf/service_plans.go
src/autoscaler/cf/service_plans_test.go
src/autoscaler/cf/testdata/service_plan.json
src/autoscaler/integration/integration_suite_test.go
src/autoscaler/testhelpers/mocks.go
src/autoscaler/testhelpers/mocks_test.go

- factored out the gets
- Refactored out the get inteface calls and added a memoiser
- Moved /v2/service_plans to /v3/service_plans

Migrated call from `/v2/service_plans/:guid` to `/v3/service_plans/:guid`

---

src/autoscaler/api/cmd/api/api_suite_test.go
src/autoscaler/cf/app.go
src/autoscaler/cf/app_test.go
src/autoscaler/cf/client.go
src/autoscaler/cf/client_test.go
src/autoscaler/cf/endpoints.go
src/autoscaler/cf/endpoints_test.go
src/autoscaler/cf/lazy.go
src/autoscaler/cf/lazy_test.go
src/autoscaler/cf/oauth.go
src/autoscaler/cf/retriever.go
src/autoscaler/cf/retriever_test.go
src/autoscaler/cf/roles.go
src/autoscaler/cf/roles_test.go
src/autoscaler/cf/service_instances.go
src/autoscaler/cf/service_instances_test.go
src/autoscaler/cf/service_plans.go
src/autoscaler/cf/service_plans_test.go
src/autoscaler/cf/testdata/endpoints.json
src/autoscaler/fakes/fake_cf_client.go
src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
src/autoscaler/integration/integration_golangapi_metricsserver_test.go
src/autoscaler/integration/integration_golangapi_scalingengine_test.go
src/autoscaler/integration/integration_golangapi_scheduler_test.go
src/autoscaler/integration/integration_suite_test.go
src/autoscaler/operator/cmd/operator/operator_suite_test.go
src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
src/autoscaler/testhelpers/mocks.go
src/autoscaler/testhelpers/mocks_test.go

- Finished implementation and tests. Fixing global tests is next
- added test for mocks

Migrating `v2/info` to `/` in v3 endpoint 

---

src/autoscaler/api/cmd/api/api_suite_test.go
src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
src/autoscaler/integration/integration_golangapi_metricsserver_test.go
src/autoscaler/integration/integration_golangapi_scalingengine_test.go
src/autoscaler/integration/integration_golangapi_scheduler_test.go
src/autoscaler/integration/integration_suite_test.go
src/autoscaler/operator/cmd/operator/operator_suite_test.go
src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
src/autoscaler/testhelpers/mocks.go
src/autoscaler/testhelpers/mocks_test.go

Add mocks for uaa and login

---

src/autoscaler/api/publicapiserver/middleware.go
src/autoscaler/cf/app.go
src/autoscaler/cf/app_integration_test.go
src/autoscaler/cf/app_processes.go
src/autoscaler/cf/app_processes_test.go
src/autoscaler/cf/app_test.go
src/autoscaler/cf/cf_suite_test.go
src/autoscaler/cf/client.go
src/autoscaler/cf/client_test.go
src/autoscaler/cf/endpoints_test.go
src/autoscaler/cf/oauth.go
src/autoscaler/cf/retriever_test.go
src/autoscaler/cf/roles_test.go
src/autoscaler/cf/service_instances_test.go
src/autoscaler/cf/service_plans_test.go
src/autoscaler/cf/testdata/test_app/deploy.sh
src/autoscaler/cf/testdata/test_app/manifest.yml
src/autoscaler/fakes/fake_cf_client.go
src/autoscaler/operator/applicationsyncer.go
src/autoscaler/scalingengine/scalingengine.go
src/autoscaler/scalingengine/scalingengine_test.go
src/autoscaler/testhelpers/mocks_test.go

- fixing the process count to just web processes.
- Fix issue #848

Fix issue with counting more than just web processes

---

src/autoscaler/helpers/httpclient.go

This PR copies the defaults for the cf-api client and uses 
- 200 idle connections per host.
- 5 second idle timeout.

Adding sensible idle connection setting to the internal client

---

src/autoscaler/cf/app_integration_test.go
src/autoscaler/cf/app_test.go
src/autoscaler/cf/drain_transport.go
src/autoscaler/cf/drain_transport_test.go
src/autoscaler/cf/helpers_stress_test.go
src/autoscaler/cf/helpers_test.go
src/autoscaler/cf/retriever.go
src/autoscaler/cf/retriever_test.go

This fixes issue https://github.com/cloudfoundry/app-autoscaler-release/issues/814

Fix for issue #814: Connection leak fix in cf api client.

---

.github/workflows/bosh-release-checks.yaml

Breaking change in https://github.com/actions/runner-images/issues/6283

Initialize homebrew

---

ci/autoscaler/scripts/deploy-autoscaler.sh
templates/app-autoscaler.yml

Fix to remove serial variable from the example template

---

ci/infrastructure/scripts/deploy-prometheus.sh

Prometheus deployment 
- uses jammy stemcell via operation file
- Upload stemcell if not found

Prometheus deployment uses jammy stemcell

---

src/autoscaler/models/security.go
src/autoscaler/testhelpers/clients.go
src/autoscaler/testhelpers/tls.go

Fix for #1084 which brough a bug in from 9.0.0 decpreaction fix.

Fix: 9.0.0 brought in mistake with TLS versions and cyphers not set correctly

---

ci/dockerfiles/autoscaler-deploy/Dockerfile
ci/dockerfiles/autoscaler-tools/Dockerfile

Fix installation of `yq` in tools image

---

src/acceptance/app/dynamic_policy_test.go
src/autoscaler/integration/integration_suite_test.go

Fixes #1059 memory utilisation tests.

Fix for memory uiltisation ooming in some environments

---

.envrc
.github/workflows/generate.yaml

for github-action that runs on more modern golang (with `go.mod`-files);

Remove unneeded sourcing of .envrc 

---

operations/add-releases.yml
templates/app-autoscaler-deployment.yml

Bump `postgres-release` to `44`

---

Makefile
src/autoscaler/api/cmd/api/main.go
src/autoscaler/cred_helper/custom_metrics_cred_helper.go
src/autoscaler/db/sqldb/factories.go
src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
src/autoscaler/metricsserver/cmd/metricsserver/main.go
src/autoscaler/operator/cmd/operator/main.go
src/autoscaler/operator/cmd/operator/operator_test.go
src/autoscaler/scalingengine/cmd/scalingengine/main.go

- refactoring policyDB and credentialProvider
Co-authored-by: Kevin Cross <kevin.cross@sap.com>
Co-authored-by: Susanne Salzmann <susanne.salzmann@sap.com>

Refactor some common funcs from application mains

---

src/autoscaler/api/broker/broker.go
src/autoscaler/api/broker/broker_test.go
src/autoscaler/api/brokerserver/broker_handler_test.go

- Fixing errors
- Fixing loging error returns and simplifying policy validation

Logging and error returns improvements

---

.github/workflows/linters.yaml

due to bhttps://github.com/reviewdog/action-eslint/issues/152

Temporarily disable `reviewdog/action-eslint`

---

.github/workflows/generate.yaml
Makefile
src/acceptance/api/api_suite_test.go
src/acceptance/app/app_suite_test.go
src/acceptance/helpers/cleanup.go
src/acceptance/helpers/org.go
src/acceptance/helpers/services.go
src/acceptance/run_performance/run_performance_suite_test.go
src/acceptance/run_performance/run_performance_test.go
src/acceptance/setup_performance/setup_performance_suite_test.go
src/acceptance/setup_performance/setup_performance_test.go
src/autoscaler/fakes/fake_envelope_processor_creator.go
src/autoscaler/fakes/fake_log_cache_creator.go
src/autoscaler/fakes/fake_metric_server_creator_creator.go

[Performance-Test] Cleanup test resources once test finishes

[Performance-Test] Cleanup test resources once test finishes

---

src/acceptance/README.md

Document how to build test app.

---

ci/autoscaler/pipeline.yml

Removed unused github-pr-resource

remove unused github-pr-resource from CI

---

.github/ISSUE_TEMPLATE/bug_report.md
operations/add-releases.yml
operations/log-cache-syslog-server.yml
templates/app-autoscaler-deployment.yml

Updates a few releases as we don't have any mechanism to update them.

Update various releases

---

operations/external-db.yml

Fixes #1559.
This seems to work for us.

external-db opsfile: update for new deployment manifest

---

Makefile

https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/release/builds/21#L65007ef6:376

Fix `*-release` make targets

---

src/autoscaler/scalingengine/scalingengine.go
src/autoscaler/scalingengine/scalingengine_test.go

The main scenario is when an app is being redeployed and the service
binding is temporarily removed during the deployment.

Correctly ignore scaling events on apps without a scaling policy

---

.editorconfig
.vscode/extensions.json
src/acceptance/app/dynamic_policy_test.go
src/acceptance/helpers/debug.go

and add additional output (app logs) on failure

Try to fix `memoryused` acceptance test

---

ci/autoscaler/pipeline.yml
ci/autoscaler/tasks/update-sdk/go_task.yml
ci/autoscaler/tasks/update-sdk/java_task.yml

Remove unnecessary inputs from concourse Golang and Java jobs

Remove unnecessary inputs from concourse Golang and Java jobs

---

ci/autoscaler/scripts/cleanup-autoscaler.sh
ci/autoscaler/scripts/common.sh

Issue when performing cleanup on concourse pipeline. See:  https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/app-autoscaler/pipelines/app-autoscaler-release/jobs/acceptance-log-cache-metron/builds/149
Perform idempotent cleanup of mtar deployment.

(fix) autoscaler 775/cleanup mtar

---

src/autoscaler/helpers/httpclient_test.go

- Replace usage of os.TempDir with os.MkdirTemp for creating temporary directories
- Add file existence assertions after creating certificate files
- Ensure proper cleanup of temporary files in AfterEach block
- Remove unused fmt import
- Add fileExists helper function to check for file existence

Refactor httpclient_test to use MkdirTemp and solve race condition when running test in parallel

---

src/autoscaler/mta.tpl.yaml

runs mta build for all modules globally

enhacement(MTA): Uses global mta builder for all module

---

devbox.lock
src/scheduler/pom.xml
src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplication.java

Spring Actuator can, if not configured correctly, expose sensitive
information.
We have not configured Actuator to expose any data, so we can just
remove it.
Remove Spring Actuator.

chore(scheduler): Remove actuator

---

devbox.d/mysql/my.cnf
devbox.json
devbox.lock
nix/flake.lock

Adds openssl to the devbox-environment, because we need it in our scripts!

Adds openssl to devbox-environment;
